import { mount, shallowMount } from "@vue/test-utils";
import Vue from "vue";
import Wizard from "~/components/Pages/Cabinet/Wizard/Wizard";

const mocks = {
    $store: {
      getters: {
        "menu/menu": [
          {
            name: "Клиент РЕСО",
            url: "/55",
            id: 55,
            icon: "",
            parentMenu: null,
            newRecord: false,
            filters: [],
            actions: [],
            tabs: [],
            isCard: false,
            isWizard: false,
            isUploader: false,
            isForm: false,
            isPortal: false,
            isTelemed: false,
            wizard: [],
            portalgrid: null,
            cardgrid: null,
            cardtemplate: null,
            newCount: null,
            children: [
              {
                name: "Личный кабинет",
                url: "/cabinet/55/0/701",
                id: 9476,
                icon: "",
                iconFileName: "profile",
                idItem: 701,
                idParent: 0,
                parentMenu: null,
                compType: 16,
                recordLoad: false,
                newRecord: false,
                filters: [],
                actions: [],
                tabs: [],
                add: false,
                edit: false,
                delete: false,
                cols: 1,
                isCard: false,
                isWizard: false,
                isUploader: false,
                isForm: false,
                isPortal: true,
                isTelemed: false,
                wizard: [],
                portalgrid: null,
                cardgrid: null,
                cardtemplate: null,
                isModal: false,
                groupmenu: "личные данные",
                isVisible: true,
                newCount: null,
                newCountColor: null,
              },
              {
                name: "Мой профиль",
                url: "/cabinet/55/0/979",
                id: 11451,
                icon: "",
                iconFileName: "customization",
                idItem: 979,
                idParent: 0,
                parentMenu: null,
                compType: 17,
                recordLoad: true,
                newRecord: false,
                filters: [],
                actions: [],
                tabs: [],
                add: false,
                edit: false,
                delete: false,
                cols: 1,
                isCard: false,
                isWizard: false,
                isUploader: false,
                isForm: false,
                isPortal: true,
                isTelemed: false,
                wizard: [],
                portalgrid: null,
                cardgrid: null,
                cardtemplate: null,
                isModal: false,
                closeAfterSave: false,
                groupmenu: "личные данные",
                isVisible: true,
                newCount: null,
                newCountColor: null,
              },
              {
                name: "Уведомления",
                url: "/cabinet/55/0/705",
                id: 9494,
                icon: "",
                iconFileName: "notifications",
                idItem: 705,
                idParent: 0,
                parentMenu: null,
                compType: 17,
                recordLoad: true,
                newRecord: false,
                filters: [],
                actions: [],
                tabs: [],
                add: false,
                edit: false,
                delete: false,
                cols: 1,
                isCard: false,
                isWizard: false,
                isUploader: false,
                isForm: false,
                isPortal: true,
                isTelemed: false,
                wizard: [],
                portalgrid: null,
                cardgrid: null,
                cardtemplate: null,
                isModal: false,
                closeAfterSave: false,
                groupmenu: "личные данные",
                isVisible: true,
                newCount: 21,
                newCountColor: "RED",
              },
              {
                name: "Мои полисы",
                url: "/cabinet/55/0/712",
                id: 9067,
                icon: "",
                iconFileName: "mypolicies",
                idItem: 712,
                idParent: 0,
                parentMenu: null,
                compType: 17,
                recordLoad: true,
                newRecord: false,
                filters: [],
                actions: [],
                tabs: [],
                add: false,
                edit: false,
                delete: false,
                cols: 1,
                isCard: false,
                isWizard: false,
                isUploader: false,
                isForm: false,
                isPortal: true,
                isTelemed: false,
                wizard: [],
                portalgrid: null,
                cardgrid: null,
                cardtemplate: null,
                isModal: false,
                closeAfterSave: false,
                groupmenu: "полисы",
                isVisible: true,
                newCount: 38,
                newCountColor: "RED",
              },
              {
                name: "Оплатить полис",
                url: "/cabinet/55/0/12",
                id: 9071,
                icon: "",
                iconFileName: "paypolicies",
                idItem: 12,
                idParent: 0,
                parentMenu: null,
                compType: 17,
                recordLoad: true,
                newRecord: false,
                filters: [],
                actions: [],
                tabs: [],
                add: false,
                edit: false,
                delete: false,
                cols: 1,
                isCard: false,
                isWizard: false,
                isUploader: false,
                isForm: false,
                isPortal: true,
                isTelemed: false,
                wizard: [],
                portalgrid: null,
                cardgrid: null,
                cardtemplate: null,
                isModal: false,
                groupmenu: "полисы",
                isVisible: true,
                newCount: 34,
                newCountColor: "RED",
              },
              {
                name: "Купить полис",
                url: "/cabinet/55/0/707",
                id: 9501,
                icon: "",
                iconFileName: "buypolicies",
                idItem: 707,
                idParent: 0,
                parentMenu: null,
                compType: 16,
                recordLoad: true,
                newRecord: false,
                filters: [],
                actions: [],
                tabs: [],
                add: false,
                edit: false,
                delete: false,
                cols: 1,
                isCard: false,
                isWizard: false,
                isUploader: false,
                isForm: false,
                isPortal: true,
                isTelemed: false,
                wizard: [],
                portalgrid: null,
                cardgrid: null,
                cardtemplate: null,
                isModal: false,
                groupmenu: "полисы",
                isVisible: true,
                newCount: null,
                newCountColor: null,
              },
              {
                name: "Заявления ОСОП",
                url: "/cabinet/55/0/1073",
                id: 12437,
                icon: "",
                iconFileName: "mypolicies",
                idItem: 1073,
                idParent: 0,
                parentMenu: null,
                compType: 17,
                recordLoad: true,
                newRecord: false,
                filters: [],
                actions: [],
                tabs: [],
                add: false,
                edit: false,
                delete: false,
                cols: 1,
                isCard: false,
                isWizard: false,
                isUploader: false,
                isForm: false,
                isPortal: true,
                isTelemed: false,
                wizard: [],
                portalgrid: null,
                cardgrid: null,
                cardtemplate: null,
                isModal: false,
                closeAfterSave: false,
                groupmenu: "заявления",
                isVisible: true,
                newCount: null,
                newCountColor: null,
              },
              {
                name: "Мои случаи",
                url: "/cabinet/55/0/713",
                id: 9068,
                icon: "",
                iconFileName: "insuredevents",
                idItem: 713,
                idParent: 0,
                parentMenu: 946,
                compType: 17,
                recordLoad: true,
                newRecord: false,
                filters: [],
                actions: [],
                tabs: [],
                add: false,
                edit: false,
                delete: false,
                cols: 1,
                isCard: false,
                isWizard: false,
                isUploader: false,
                isForm: false,
                isPortal: true,
                isTelemed: false,
                wizard: [],
                portalgrid: null,
                cardgrid: null,
                cardtemplate: null,
                isModal: false,
                groupmenu: "страховой случай",
                isVisible: true,
                newCount: null,
                newCountColor: null,
              },
              {
                name: "Здоровье",
                url: "/cabinet/55/0/883",
                id: 12602,
                icon: "",
                iconFileName: "dms3",
                idItem: 883,
                idParent: 0,
                parentMenu: 872,
                compType: 17,
                recordLoad: false,
                newRecord: false,
                filters: [],
                actions: [],
                tabs: [],
                add: true,
                edit: true,
                delete: false,
                cols: 1,
                isCard: false,
                isWizard: false,
                isUploader: false,
                isForm: false,
                isPortal: true,
                isTelemed: false,
                wizard: [],
                portalgrid: null,
                cardgrid: null,
                cardtemplate: null,
                isModal: false,
                closeAfterSave: false,
                groupmenu: "ДМС",
                isVisible: true,
                newCount: null,
                newCountColor: null,
              },
              {
                name: "Оплата франшизы",
                url: "/cabinet/55/0/899",
                id: 11935,
                icon: "",
                iconFileName: "paypolicies",
                idItem: 899,
                idParent: 0,
                parentMenu: null,
                compType: 17,
                recordLoad: false,
                newRecord: false,
                filters: [],
                actions: [],
                tabs: [],
                add: true,
                edit: true,
                delete: false,
                cols: 1,
                isCard: false,
                isWizard: false,
                isUploader: false,
                isForm: false,
                isPortal: true,
                isTelemed: false,
                wizard: [],
                portalgrid: null,
                cardgrid: null,
                cardtemplate: null,
                isModal: false,
                closeAfterSave: false,
                groupmenu: "ДМС",
                isVisible: true,
                newCount: null,
                newCountColor: null,
              },
              {
                name: "Мои осмотры",
                url: "/cabinet/55/0/1080",
                id: 12647,
                icon: "",
                idItem: 1080,
                idParent: 0,
                parentMenu: 1078,
                compType: 17,
                recordLoad: true,
                newRecord: false,
                filters: [],
                actions: [],
                tabs: [],
                add: false,
                edit: false,
                delete: false,
                cols: 1,
                isCard: false,
                isWizard: false,
                isUploader: false,
                isForm: false,
                isPortal: true,
                isTelemed: false,
                wizard: [],
                portalgrid: null,
                cardgrid: null,
                cardtemplate: null,
                isModal: false,
                closeAfterSave: false,
                groupmenu: "осмотры",
                isVisible: true,
                newCount: null,
                newCountColor: null,
              },
              {
                name: "Ввод данных",
                url: "/cabinet/55/0/1089",
                id: 12820,
                icon: "",
                idItem: 1089,
                idParent: 0,
                parentMenu: null,
                compType: 9,
                recordLoad: true,
                newRecord: false,
                filters: [],
                actions: [],
                tabs: [],
                add: true,
                edit: true,
                delete: false,
                cols: 1,
                isCard: false,
                isWizard: false,
                isUploader: false,
                isForm: true,
                isPortal: false,
                isTelemed: false,
                wizard: [],
                portalgrid: null,
                cardgrid: null,
                cardtemplate: null,
                isModal: false,
                closeAfterSave: false,
                groupmenu: "ОСАГО",
                newCount: null,
                newCountColor: null,
              },
              {
                name: "Полис ОСАГО",
                url: "/cabinet/55/0/1081",
                id: 12819,
                icon: "",
                idItem: 1081,
                idParent: 0,
                parentMenu: null,
                compType: 14,
                recordLoad: false,
                newRecord: false,
                filters: [],
                actions: [],
                tabs: [],
                add: false,
                edit: false,
                delete: false,
                cols: 1,
                isCard: false,
                isWizard: true,
                isUploader: false,
                isForm: false,
                isPortal: false,
                isTelemed: false,
                wizard: [
                  { name: "Ввод данных", idItem: 1089, id: 4540, list: false, order: 1 },
                  { name: "Водители", idItem: 1093, id: 4541, list: false, order: 2 },
                  { name: "Сроки страхования", idItem: 1096, id: 4542, list: false, order: 3 },
                  { name: "Точный расчет", idItem: 1098, id: 4539, list: false, order: 4 },
                  { name: "Загрузка документов", idItem: 1100, id: 4566, list: false, order: 5 },
                ],
                portalgrid: null,
                cardgrid: null,
                cardtemplate:
                  '<!--<div v-if="tabs.length > 1">\n <div class="row step-block osago mt-4  justify-content-center">\n  <template  v-for="(item, index) in tabs">\n   <div v-on="item.order < currentTab.order ? {click: ()=> $router.push(getURL(item,index))}:{}" class="col-1 text-center position-relative" :class="{ active: item.order <= currentTab.order }">\n \n   <div v-if="item.order === 2" class="step" :data-step="4"></div>\n   <div v-else-if="item.order === 3" class="step" :data-step="5"></div>\n   <div v-else class="step" :data-step="item.order"></div>\n    <span class="step-text">{{ item.name }}</span>\n   </div>\n   <div v-if="tabs.length !== index + 1" class="col-auto" :class="{ active: item.order < currentTab.order }">\n    <div class="dotted"></div>\n   </div>\n  </template>   \n </div>\n <div class="d-none"><h3>{{currentTab.name }} - шаг {{currentTab.order > tabs.length ? tabs.length : currentTab.order }} из {{tabs.length}}</h3></div>\n</div -->',
                isModal: false,
                closeAfterSave: false,
                groupmenu: "ОСАГО",
                isVisible: false,
                newCount: null,
                newCountColor: null,
              },
            ],
          },
        ],
        "wizard/iconTabsCount": 3,
        "wizard/getForceUpdate": true,
        "menu/getMenuById": () => ({"LSHOWWIZARDROUTE":true,"IDADMMENUTYPE":14,"SGROUPMENU":"Электронное урегулирование ОСАГО СВУ","NCOLCOUNT":1,"LMODALFORMSTYLE":false,"LUSEBLOCK":false,"LCLOSEAFTERSAVE":false,"LNEW":false,"LEDIT":false,"ID":12433,"IDITEM":1053,"LSHOW":true,"ONETOMANYCUR":[],"IDPARENT":0,"LNEWRECORDMETHOD":false,"LSHOWLISTROUTE":true,"LSHOWVUE":false,"WIZARDCUR":[{"MENUCUR":[{"LDELETE":false,"IDADMMENUTYPE":9,"SNAME":"Основные данные еУУ ОСАГО СВУ","LMODALFORMSTYLE":false,"NONETOMANY":0,"LNEW":true,"LEDIT":true,"LNOTCARD":false,"ACTIONSCUR":[{"LUSEINCARD":true,"LIDLIST":false,"LSELECTDEFAULT":false,"LINBUTTONS":false,"NITEM":1054,"LCREATEBUTTON":false,"LCHECKACCESS":false,"LFROMDATASET":true,"LINLIST":false,"LOUTPARAM":false,"LWITHCOMMIT":false,"ID":45027,"LCURWINDOW":true,"LMULTISELECT":false,"SCONST":"Mobile.ClientUtils.SendEmail","SNAME":"Получить код","LFREEZONE":false,"LREQUESTCODE":false,"LCLOSEAFTER":false,"LINACTIONS":true,"LREFRESH":false,"REL":"45BC690BDA18BFEB6846526D178BC0FA","SFIELD":"id","NTYPE":4,"LHIDEDLG":true,"IDADMMODULE":55,"LNEEDPARAM":true,"LHIDEINLIST":false,"LTOOLBAR":false}],"ID":12434,"LFIRSTLOADRECORD":true,"IDITEM":1054,"ONETOMANYCUR":[],"IDPARENT":0,"LPRINT":false,"LNEWRECORDMETHOD":true}],"SNAME":"Основные данные","NORDER":1,"LOPENLIST":false,"ID":4263,"NITEMPARENTMENU":1053,"NITEM":1054,"IDADMMODULE":55},{"MENUCUR":[{"LDELETE":false,"IDADMMENUTYPE":502,"SNAME":"Загрузка документов еУУ ОСАГО СВУ","LMODALFORMSTYLE":false,"NONETOMANY":0,"LNEW":true,"LEDIT":true,"LNOTCARD":false,"ACTIONSCUR":[],"ID":12435,"LFIRSTLOADRECORD":true,"IDITEM":1055,"ONETOMANYCUR":[],"IDPARENT":0,"LPRINT":false,"LNEWRECORDMETHOD":false}],"SNAME":"Загрузка документов","NORDER":2,"LOPENLIST":true,"ID":4264,"NITEMPARENTMENU":1053,"NITEM":1055,"IDADMMODULE":55},{"MENUCUR":[{"LDELETE":false,"IDADMMENUTYPE":3,"SNAME":"Отправка заявления еУУ ОСАГО СВУ","LMODALFORMSTYLE":true,"NONETOMANY":0,"LNEW":true,"LEDIT":true,"LNOTCARD":false,"ACTIONSCUR":[{"LUSEINCARD":true,"LIDLIST":false,"LSELECTDEFAULT":false,"LINBUTTONS":false,"NITEM":1056,"LCREATEBUTTON":true,"LCHECKACCESS":false,"LFROMDATASET":false,"LINLIST":false,"LOUTPARAM":true,"LWITHCOMMIT":false,"ID":44420,"LCURWINDOW":false,"LMULTISELECT":false,"SCONST":"v4.pkg_eclaims_osago.SendEAdjustmentToGosKeyOut","SNAME":"Отправить заявление на подпись в Госключ","LFREEZONE":false,"LREQUESTCODE":false,"LCLOSEAFTER":false,"LINACTIONS":true,"LREFRESH":false,"REL":"55AEE2567BE0BC73F70EEA5D1214BE15","SFIELD":"id","NTYPE":4,"LHIDEDLG":true,"IDADMMODULE":55,"LNEEDPARAM":false,"LHIDEINLIST":false,"LTOOLBAR":false},{"LUSEINCARD":true,"LIDLIST":false,"LSELECTDEFAULT":false,"LINBUTTONS":false,"NITEM":1056,"LCREATEBUTTON":true,"LCHECKACCESS":false,"LFROMDATASET":false,"LINLIST":false,"LOUTPARAM":true,"LWITHCOMMIT":false,"ID":44421,"LCURWINDOW":false,"LMULTISELECT":false,"SCONST":"v4.pkg_eclaims_osago.GetLinkEsia","SNAME":"Авторизоваться через Госуслуги","LFREEZONE":false,"LREQUESTCODE":false,"LCLOSEAFTER":false,"LINACTIONS":true,"LREFRESH":false,"REL":"EC84F7FBF5A289C9B169C70865C27D63","SFIELD":"id","NTYPE":4,"LHIDEDLG":true,"IDADMMODULE":55,"LNEEDPARAM":false,"LHIDEINLIST":false,"LTOOLBAR":false}],"ID":12436,"LFIRSTLOADRECORD":true,"IDITEM":1056,"ONETOMANYCUR":[],"IDPARENT":0,"LPRINT":false,"LNEWRECORDMETHOD":false}],"SNAME":"Отправка заявления","NORDER":3,"LOPENLIST":false,"ID":4265,"NITEMPARENTMENU":1053,"NITEM":1056,"IDADMMODULE":55}],"LDELETE":false,"FILTERCUR":[],"SNAME":"Электронное урегулирование ОСАГО СВУ","LSHOWCARDROUTE":true,"NONETOMANY":0,"LCANLIST":false,"SVJCARDTEMPLATE":"<div v-if=\"tabs.length > 1\">\n <div class=\"row step-block osago mt-4  justify-content-center\">\n  <template  v-for=\"(item, index) in tabs\">\n   <div v-on=\"item.order < currentTab.order ? {click: ()=> $router.push(getURL(item,index))}:{}\" class=\"col-1 text-center position-relative\" :class=\"{ active: item.order <= currentTab.order }\">\n \n   <div v-if=\"item.order === 2\" class=\"step\" :data-step=\"4\"></div>\n   <div v-else-if=\"item.order === 3\" class=\"step\" :data-step=\"5\"></div>\n   <div v-else class=\"step\" :data-step=\"item.order\"></div>\n    <span class=\"step-text\">{{ item.name }}</span>\n   </div>\n   <div v-if=\"tabs.length !== index + 1\" class=\"col-auto\" :class=\"{ active: item.order < currentTab.order }\">\n    <div class=\"dotted\"></div>\n   </div>\n  </template>   \n </div>\n <div class=\"d-none\"><h3>{{currentTab.name }} - шаг {{currentTab.order > tabs.length ? tabs.length : currentTab.order }} из {{tabs.length}}</h3></div>\n</div>\n","LNOTCARD":false,"ACTIONSCUR":[],"LFIRSTLOADRECORD":false,"LTABBED":true,"LPRINT":false})
      },
      commit: () => {},
    },
    $route: {
      params: { idItem: 1054, idWizard: 1053 },
    },
  };

describe("Wizard", () => {
  test("If tabs les then IconTabsCount isWizardProgressBar === false ", () => {
    const wrapper = shallowMount(Wizard, {
      mocks,
    });

    expect(wrapper.vm.isWizardProgressBar).toBeFalsy();
  });

  describe("geForceNextStep", () => {
    const tabs =       [{"name":"Сведения о ТС","idItem":1105,"id":4540,"list":false,"order":1},{"name":"Документы ТС","idItem":1106,"id":4541,"list":false,"order":2},{"name":"Страхователь/Собственник","idItem":1107,"id":4542,"list":false,"order":3},{"name":"Водители","idItem":1093,"id":4539,"list":false,"order":4},{"name":"Сроки страхования","idItem":1096,"id":4646,"list":false,"order":5},{"name":"Точный расчет","idItem":1098,"id":4647,"list":false,"order":6},{"name":"Загрузка документов","idItem":1100,"id":4648,"list":false,"order":7},{"name":"Подтверждение","idItem":1101,"id":4649,"list":false,"order":8},{"name":"Оплата","idItem":1102,"id":4650,"list":false,"order":9}];
    const currentTab = {"name":"Сведения о ТС","idItem":1105,"id":4540,"list":false,"order":1};

    test("Должен вернуться шаг следующий полсе текущего если wizard/getForceUpdate = true" , () => {
      const mockWrapper = Vue.extend({
        extends: Wizard,
        computed: {
          tabs,
          currentTab
        }
      });
      const wrapper = shallowMount(Wizard, { mocks });

      jest.spyOn(wrapper.vm, "tabs", "get").mockReturnValue([{"name":"Сведения о ТС","idItem":1105,"id":4540,"list":false,"order":1},{"name":"Документы ТС","idItem":1106,"id":4541,"list":false,"order":2},{"name":"Страхователь/Собственник","idItem":1107,"id":4542,"list":false,"order":3},{"name":"Водители","idItem":1093,"id":4539,"list":false,"order":4},{"name":"Сроки страхования","idItem":1096,"id":4646,"list":false,"order":5},{"name":"Точный расчет","idItem":1098,"id":4647,"list":false,"order":6},{"name":"Загрузка документов","idItem":1100,"id":4648,"list":false,"order":7},{"name":"Подтверждение","idItem":1101,"id":4649,"list":false,"order":8},{"name":"Оплата","idItem":1102,"id":4650,"list":false,"order":9}]);
      jest.spyOn(wrapper.vm, "currentTab", "get").mockReturnValue({"name":"Сведения о ТС","idItem":1105,"id":4540,"list":false,"order":1});

      expect(wrapper.vm.geForceNextStep().order).toBe(2);
    });

    test("Должен вернуться null если wizard/getForceUpdate = false" , () => {
      const newMocks = {...mocks};

      newMocks.$store.getters["wizard/getForceUpdate"] = false;
      const mockWrapper = Vue.extend({
        extends: Wizard,
        computed: {
          tabs,
          currentTab
        }
      });
      const wrapper = shallowMount(Wizard, { mocks: newMocks });

      jest.spyOn(wrapper.vm, "tabs", "get").mockReturnValue([{"name":"Сведения о ТС","idItem":1105,"id":4540,"list":false,"order":1},{"name":"Документы ТС","idItem":1106,"id":4541,"list":false,"order":2},{"name":"Страхователь/Собственник","idItem":1107,"id":4542,"list":false,"order":3},{"name":"Водители","idItem":1093,"id":4539,"list":false,"order":4},{"name":"Сроки страхования","idItem":1096,"id":4646,"list":false,"order":5},{"name":"Точный расчет","idItem":1098,"id":4647,"list":false,"order":6},{"name":"Загрузка документов","idItem":1100,"id":4648,"list":false,"order":7},{"name":"Подтверждение","idItem":1101,"id":4649,"list":false,"order":8},{"name":"Оплата","idItem":1102,"id":4650,"list":false,"order":9}]);
      jest.spyOn(wrapper.vm, "currentTab", "get").mockReturnValue({"name":"Сведения о ТС","idItem":1105,"id":4540,"list":false,"order":1});

      expect(wrapper.vm.geForceNextStep()).toBe(null);
    });
  })
});
