stages:
  - "build"
  - "deploy"
  - "prod-rollback"
  # - "check-version"
  # - "mr-test"
  - "version-bump"
  - "cleanup"

# PROJECT_WRITE_REPOSITORY_TOKEN необходимо создать здесь https://git.reso.ru/web/nuxt-vue/-/settings/access_tokens
# с ролью maintainer и правами read_repository и write_repository
# далее добавить сюда https://git.reso.ru/web/nuxt-vue/-/settings/ci_cd как переменную PROJECT_WRITE_REPOSITORY_TOKEN
version-bump-master:
  image: node:20
  stage: version-bump
  variables:
    CI_NAME: gitlab
    CI_EMAIL: ${CI_NAME}@reso.ru
  script:
    - git config --global user.email $CI_EMAIL
    - git config --global user.name $CI_NAME
    - git config receive.advertisePushOptions true
    - git config --global http.sslVerify false
    - git checkout -B "$CI_COMMIT_REF_NAME" "$CI_COMMIT_SHA"
    - PROJECT_VERSION_PREFIX=$(grep version package.json | awk -F':' '{ print $2 }' | sed 's/[", ]//g' | sed 's/.[^.]*$//')
    - CURRENT_DATE_PREFIX=$(date +%y.%-m)
    - echo "project version is [$PROJECT_VERSION_PREFIX]"
    - echo "current date is [$CURRENT_DATE_PREFIX]"
    - if [[ "$PROJECT_VERSION_PREFIX" == "$CURRENT_DATE_PREFIX" ]]; then npm version patch; else npm version "$CURRENT_DATE_PREFIX.1"; fi
    - git push "https://$CI_NAME:$PROJECT_WRITE_REPOSITORY_TOKEN@$CI_SERVER_HOST/$CI_PROJECT_PATH.git" --follow-tags $CI_COMMIT_BRANCH:$CI_COMMIT_BRANCH
  rules:
    - if: '$GITLAB_USER_NAME != "PROJECT_WRITE_REPOSITORY_TOKEN" && $CI_COMMIT_REF_NAME == "master" && $CI_PIPELINE_SOURCE == "push"'

docker-build-master:
  image: docker:latest
  stage: build
  services:
    - name: docker:dind
      command: ["--registry-mirror", "https://docker.reso.ru"]
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - export VERSION=$(cat package.json | grep version | head -1 | awk -F= "{ print $2 }" | sed 's/[version:,\",]//g' | tr -d '[[:space:]]')
    - docker pull "$CI_REGISTRY_IMAGE/nuxt-server:$CI_COMMIT_SHORT_SHA" || true
    - docker build --pull --build-arg APP_VERSION=$VERSION --build-arg APP_VERSION_BRANCH=$CI_COMMIT_REF_NAME --build-arg APP_VERSION_DATE=$CI_COMMIT_TIMESTAMP --tag "$CI_REGISTRY_IMAGE/nuxt-server:$CI_COMMIT_SHORT_SHA" .
    - docker push "$CI_REGISTRY_IMAGE/nuxt-server:$CI_COMMIT_SHORT_SHA"
  rules:
    # Защита от выполнения при слиянии
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    # Будет выполняться на каждый коммит в ветку, а в мастере только на любых тэгах (к примеру, v1.0.1)
    - if: '$CI_COMMIT_REF_NAME != "master"'
  tags:
    - docker

# Сборка сайта ветки вида https://lk2-1001.dev.reso.ru
include:
  - local: ".gitlab-ci.deploy-branch.yml"

# check-stand-version:
#   image: curlimages/curl:7.78.0
#   stage: check-version
#   script:
#     - sleep 120
#     - echo $CI_COMMIT_BRANCH
#     - if echo "$CI_COMMIT_BRANCH" | grep -Eq '^LK2-[0-9]{4}$'; then BRANCH_NAME_LOWER=$(echo "$CI_COMMIT_BRANCH" | tr '[:upper:]' '[:lower:]'); else echo "Branch name format is invalid"; exit 1; fi
#     - ACTUAL_STAND_VERSION=$(curl -k https://$BRANCH_NAME_LOWER-prod.dev.reso.ru/api/version?hash)
#     - if [ $ACTUAL_STAND_VERSION == $CI_COMMIT_SHORT_SHA ]; then echo "Выкладка на стенд версии $CI_COMMIT_SHORT_SHA успешна!"; else echo "Версия не корректна!"; exit 1; fi
#   rules:
#     - if: $CI_PIPELINE_SOURCE == "merge_request_event"
#       when: never
#     - if: '$CI_COMMIT_REF_NAME != "master"'
#   tags:
#     - docker

# mr-test-check:
#   image: alpine:3.18
#   stage: mr-test
#   before_script:
#     - apk add --no-cache curl jq
#     - BRANCH_MR_EXIST=$(curl --silent --header "PRIVATE-TOKEN:$GITLAB_TOKEN" "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/merge_requests?state=opened&source_branch=$CI_COMMIT_REF_NAME" | jq '. | length')
#     - if [[ $BRANCH_MR_EXIST == 0 ]]; then echo "Merge Request для ветки $CI_COMMIT_REF_NAME не создан, запуск тестов отменен" kill $$; else echo "Тесты будут запущены!"; fi
#   script:
#     - sleep 60
#     - if echo "$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME" | grep -Eq '^LK2-[0-9]{4}$'; then BRANCH_NAME_LOWER=$(echo "$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME" | tr '[:upper:]' '[:lower:]'); else BRANCH_NAME_LOWER=$(echo "$CI_COMMIT_BRANCH" | tr '[:upper:]' '[:lower:]');  fi
#     - RESPONSE=$(curl -X POST -F token=$TEST_PROJECT_TRIGGER_TOKEN -F ref=master -F "variables[MR_SOURCE_BRANCH]=$CI_COMMIT_REF_NAME" -F "variables[LK2_URL]=https://$BRANCH_NAME_LOWER-prod.dev.reso.ru" -F "variables[IGNORE_CERT_ERRORS]=true" https://git.reso.ru/api/v4/projects/274/trigger/pipeline)
#     - PIPELINE_ID=$(echo "$RESPONSE" | jq -r '.id')
#     - echo "Waiting for test pipeline $PIPELINE_ID to finish..."
#     - while true; do STATUS=$(curl --silent --header "PRIVATE-TOKEN:$TEST_PRJ_ACCESS_TOKEN" "https://git.reso.ru/api/v4/projects/274/pipelines/$PIPELINE_ID" | jq -r '.status'); [[ "$STATUS" != "$PREVIOS_PIPELINE_STATUS" ]] && echo "Pipeline status - $STATUS"; PREVIOS_PIPELINE_STATUS=$STATUS; [[ "$STATUS" == "success" ]] && echo "Тесты пройдены успешно!" && exit 0; [[ "$STATUS" == "failed" || "$STATUS" == "canceled" || "$STATUS" == "null" ]] && echo "Тесты завершились со статусом - $STATUS. Подробности можно посмотреть - https://git.reso.ru/web/lk2-ui-test/-/pipelines/$PIPELINE_ID" && exit 1; sleep 10; done
#   rules:
#     - if: $CI_PIPELINE_SOURCE == "merge_request_event"
#       when: never
#     - if: $CI_COMMIT_REF_NAME != "master"
#   tags:
#     - docker

release.reso.ru:
  image: curlimages/curl:7.78.0
  stage: deploy
  script:
    - curl -X POST -F token=$INFRASTRUCTURE_TRIGGER_TOKEN -F ref=master -F "variables[LK2_RELEASE_VERSION]=$CI_COMMIT_SHORT_SHA" https://git.reso.ru/api/v4/projects/167/trigger/pipeline
  rules:
    # - if: $CI_COMMIT_REF_NAME == "master" && $DEPLOY_LATEST_MASTER
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - if: '$CI_COMMIT_REF_NAME != "master"'
      when: manual
      allow_failure: true
  tags:
    - docker

release-actuary.reso.ru:
  image: curlimages/curl:7.78.0
  stage: deploy
  script:
    - curl -X POST -F token=$INFRASTRUCTURE_TRIGGER_TOKEN -F ref=master -F "variables[LK2_RELEASE_ACTUARY_VERSION]=$CI_COMMIT_SHORT_SHA" https://git.reso.ru/api/v4/projects/167/trigger/pipeline
  rules:
    # - if: $CI_COMMIT_REF_NAME == "master" && $DEPLOY_LATEST_MASTER
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - if: '$CI_COMMIT_REF_NAME != "master"'
      when: manual
      allow_failure: true
  tags:
    - docker

test86-new.reso.ru:
  image: curlimages/curl:7.78.0
  stage: deploy
  script:
    - curl -X POST -F token=$INFRASTRUCTURE_TRIGGER_TOKEN -F ref=master -F "variables[LK2_TEST_X86_VERSION]=$CI_COMMIT_SHORT_SHA" https://git.reso.ru/api/v4/projects/167/trigger/pipeline
  rules:
    # - if: $CI_COMMIT_REF_NAME == "master" && $DEPLOY_LATEST_MASTER
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - if: '$CI_COMMIT_REF_NAME != "master"'
      when: manual
      allow_failure: true
  tags:
    - docker

new.reso.ru:
  image: curlimages/curl:7.78.0
  stage: deploy
  script:
    - curl -X POST -F token=$INFRASTRUCTURE_TRIGGER_TOKEN -F ref=master -F "variables[LK2_TEST_VERSION]=$CI_COMMIT_SHORT_SHA" https://git.reso.ru/api/v4/projects/167/trigger/pipeline
  rules:
    - if: $CI_COMMIT_REF_NAME =~ /^v\d.+/
    - if: $CI_COMMIT_REF_NAME == "production"
    - if: $CI_COMMIT_REF_NAME == "master" && $DEPLOY_LATEST_MASTER
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - if: '$CI_COMMIT_REF_NAME != "master"'
      when: manual
      allow_failure: true
  tags:
    - docker

test-new.reso.ru:
  image: curlimages/curl:7.78.0
  stage: deploy
  script:
    - curl -X POST -F token=$INFRASTRUCTURE_TRIGGER_TOKEN -F ref=master -F "variables[LK2_ACTUARY_VERSION]=$CI_COMMIT_SHORT_SHA" https://git.reso.ru/api/v4/projects/167/trigger/pipeline
  rules:
    - if: $CI_COMMIT_REF_NAME == "master" && $DEPLOY_LATEST_MASTER
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - if: '$CI_COMMIT_REF_NAME != "master"'
      when: manual
      allow_failure: true
  tags:
    - docker

reso.ru:
  image: curlimages/curl:7.78.0
  stage: prod-rollback
  script:
    - if [[ $GITLAB_USER_LOGIN != "tafaa" ]] && [[ $GITLAB_USER_LOGIN != "podns" ]] && [[ $GITLAB_USER_LOGIN != "ionka" ]]; then echo "❌ У вас нет прав на запуск этого джоба!"; exit 1; fi
    - ACTUALVERSION=$(curl -k https://reso.ru/api/version?appBranch)
    - echo "${ACTUALVERSION#v}" | IFS='.' read -r actual_year actual_month actual_commit
    - echo "${CI_COMMIT_SHORT_SHA#v}" | IFS='.' read -r new_year new_month new_commit
    - curl -X POST -F token=$INFRASTRUCTURE_TRIGGER_TOKEN -F ref=master -F "variables[LK2_PRODUCTION_VERSION]=$CI_COMMIT_SHORT_SHA" https://git.reso.ru/api/v4/projects/167/trigger/pipeline
    - sleep 90
    - if (( new_year < actual_year )) || (( new_year == actual_year && new_month < actual_month )) || (( new_year == actual_year && new_month == actual_month && new_commit < actual_commit)); then curl -X POST -F token=$TEST_PROJECT_TRIGGER_TOKEN -F ref=master -F "variables[RESORU_ROLLBACK]=true" -F "variables[LK2_URL]=https://reso.ru" https://git.reso.ru/api/v4/projects/274/trigger/pipeline ; fi
  rules:
    - if: $CI_COMMIT_REF_NAME == "production"
    - if: $CI_COMMIT_REF_NAME =~ /^v\d.+/
      when: manual
  tags:
    - docker
