stages:
  - pre_deploy
  - deploy

build_compoments:
  image: node:12
  stage: pre_deploy
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
  script:
    - npm install
    - npm test
    - cd components-vue2
    - npm install
    - npm run component
  artifacts:
    paths:
      - static/js
    untracked: false
    expire_in: 1 days
  tags:
    - git-docker

deploy_staging:
  image: instrumentisto/rsync-ssh
  stage: deploy
  cache: {}
  script:
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - chmod 600 $PRIVATE_KEY
    - ssh-add $PRIVATE_KEY
    - ssh-keyscan -H -p $TEST_PORT $TEST_HOST >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - rsync --recursive --delete-after --rsh "ssh -p $TEST_PORT" . nodejs@$TEST_HOST:nuxt-vue
    - ssh -p $TEST_PORT nodejs@$TEST_HOST -- '\. ~/.nvm/nvm.sh; cd ~/nuxt-vue; npm install'
    - ssh -p $TEST_PORT nodejs@$TEST_HOST -- '\. ~/.nvm/nvm.sh; cd ~/nuxt-vue; npm run build'
    - ssh -p $TEST_PORT nodejs@$TEST_HOST -- '\. ~/.nvm/nvm.sh; pm2 restart all'
  environment:
    name: test
    url: http://new.reso.ru/
  dependencies:
    - build_compoments
  only:
    - master
  tags:
    - git-docker
