import { mount } from "@vue/test-utils";
import PriceComponent from "./PriceComponent.vue";

describe("PriceComponent", () => {
  const propsData = {
    data: {
      type: "VueComponent",
      id: "746",
      fieldId: 31805,
      cols: 12,
      colSm: 12,
      colMd: 12,
      isMask: false,
      colLg: 12,
      width: "100%",
      name: "PriceComponent",
      cssClass: "price",
      webId: "",
      visible: true,
      required: false,
      page: 1,
      readonly: true,
      control: null,
      state: null,
      checked: null,
      error: null,
      isRelation: false,
      fieldRelation: null,
      isTab: true,
    },
  };
  const formData = [
    {
      label: "Страховой полис Антиклещ",
      type: "splitter",
      id: "746",
      fieldId: 36521,
      cols: 12,
      colSm: 12,
      colMd: 12,
      isMask: false,
      colLg: 12,
      width: "100%",
      name: "Separator_AntiKlesh_746_01",
      cssClass: "",
      webId: "",
      visible: true,
      required: false,
      page: 0,
      readonly: false,
      control: null,
      state: null,
      checked: null,
      error: null,
      isRelation: false,
      fieldRelation: null,
      isTab: true,
    },
    {
      label: "Страхователь",
      value:
        "Иванов Иван Иванович, 10.11.1979<br>Адрес: 143903,Московская обл, г Балашиха, пр-кт Ленина, д 77<br>Паспорт Гражданина РФ: 1222 971135 (Россия)",
      type: "label",
      structType: "string",
      id: "746",
      fieldId: 31801,
      cols: 12,
      colSm: 12,
      colMd: 12,
      isMask: false,
      colLg: 12,
      width: "100%",
      name: "SPHOLDER",
      cssClass: "",
      webId: "",
      visible: true,
      required: false,
      page: 0,
      readonly: true,
      control: null,
      state: null,
      checked: null,
      error: null,
      isRelation: false,
      fieldRelation: null,
      isTab: true,
    },
    {
      label: "Застрахованный",
      value: "<ul><li>Иванов Иван Иванович, 10.11.1979</li></ul>",
      type: "label",
      structType: "string",
      id: "746",
      fieldId: 31802,
      cols: 12,
      colSm: 12,
      colMd: 12,
      isMask: false,
      colLg: 12,
      width: "100%",
      name: "SINSURED",
      cssClass: "",
      webId: "",
      visible: true,
      required: false,
      page: 0,
      readonly: true,
      control: null,
      state: null,
      checked: null,
      error: null,
      isRelation: false,
      fieldRelation: null,
      isTab: true,
    },
    {
      label: "Страховая программа",
      value:
        "<ul><li>Амбулаторная помощь при укусе клеща<br></li><li>Экстренный стационар<br></li><li>Реабилитация после тяжелой формы энцефалита</li></ul>",
      type: "label",
      structType: "string",
      id: "746",
      fieldId: 48510,
      cols: 12,
      colSm: 12,
      colMd: 12,
      isMask: false,
      colLg: 12,
      width: "100%",
      name: "PROGRAM_INFO",
      cssClass: "",
      webId: "",
      visible: true,
      required: false,
      page: 0,
      readonly: true,
      control: null,
      state: null,
      checked: null,
      error: null,
      isRelation: false,
      fieldRelation: null,
      isTab: true,
    },
    {
      label: "Сроки страхования",
      value: "30.07.2024 - 29.07.2025",
      type: "label",
      structType: "string",
      id: "746",
      fieldId: 36523,
      cols: 12,
      colSm: 12,
      colMd: 12,
      isMask: false,
      colLg: 12,
      width: "100%",
      name: "SINS_PERIOD",
      cssClass: "",
      webId: "",
      visible: true,
      required: false,
      page: 0,
      readonly: false,
      control: null,
      state: null,
      checked: null,
      error: null,
      isRelation: false,
      fieldRelation: null,
      isTab: true,
    },
    {
      label: "Внести изменения",
      type: "button",
      id: "746",
      fieldId: 48569,
      cols: 6,
      colSm: 12,
      colMd: 12,
      isMask: false,
      colLg: 12,
      width: "60%",
      name: "Item39766",
      cssClass: "btn-secondary w-90",
      webId: "",
      visible: true,
      required: false,
      page: 0,
      readonly: false,
      control: null,
      state: null,
      checked: null,
      error: null,
      isRelation: false,
      fieldRelation: null,
      isTab: true,
    },
    {
      label: "Распечатать проект",
      type: "button",
      id: "746",
      fieldId: 48513,
      cols: 6,
      colSm: 12,
      colMd: 12,
      isMask: false,
      colLg: 12,
      width: "60%",
      name: "Item39765",
      cssClass: "btn-secondary w-90",
      webId: "",
      visible: true,
      required: false,
      page: 0,
      readonly: false,
      control: null,
      state: null,
      checked: null,
      error: null,
      isRelation: false,
      fieldRelation: null,
      isTab: true,
    },
    {
      label: "Подтвердить данные",
      type: "button",
      id: "746",
      fieldId: 31808,
      cols: 3,
      colSm: 12,
      colMd: 12,
      isMask: false,
      colLg: 12,
      width: "100%",
      name: "Item35683",
      cssClass: "",
      webId: "",
      visible: false,
      required: false,
      page: 0,
      readonly: false,
      control: null,
      state: null,
      checked: null,
      error: null,
      isRelation: false,
      fieldRelation: null,
      isTab: true,
    },
    {
      label: "Распечатать полис",
      type: "button",
      id: "746",
      fieldId: 31807,
      cols: 6,
      colSm: 12,
      colMd: 12,
      isMask: false,
      colLg: 12,
      width: "60%",
      name: "Item35684",
      cssClass: "btn-secondary w-90",
      webId: "",
      visible: false,
      required: false,
      page: 0,
      readonly: false,
      control: null,
      state: null,
      checked: null,
      error: null,
      isRelation: false,
      fieldRelation: null,
      isTab: true,
    },
    {
      label: "Оплата полиса",
      type: "splitter",
      id: "746",
      fieldId: 36522,
      cols: 12,
      colSm: 12,
      colMd: 12,
      isMask: false,
      colLg: 12,
      width: "100%",
      name: "Separator_Antiklesh_746_05",
      cssClass: "pay_block",
      webId: "",
      visible: true,
      required: false,
      page: 1,
      readonly: false,
      control: null,
      state: null,
      checked: null,
      error: null,
      isRelation: false,
      fieldRelation: null,
      isTab: true,
    },
    {
      type: "VueComponent",
      id: "746",
      fieldId: 31805,
      cols: 12,
      colSm: 12,
      colMd: 12,
      isMask: false,
      colLg: 12,
      width: "100%",
      name: "PriceComponent",
      cssClass: "price",
      webId: "",
      visible: true,
      required: false,
      page: 1,
      readonly: true,
      control: null,
      state: null,
      checked: null,
      error: null,
      isRelation: false,
      fieldRelation: null,
      isTab: true,
    },
    {
      label: "Валюта",
      type: "label",
      id: "746",
      fieldId: 31804,
      cols: 4,
      colSm: 12,
      colMd: 12,
      isMask: false,
      colLg: 12,
      width: "100%",
      name: "FKIDCURRENCY",
      cssClass: "",
      webId: "",
      visible: false,
      required: false,
      page: 1,
      readonly: true,
      control: null,
      state: null,
      checked: null,
      error: null,
      isRelation: false,
      fieldRelation: null,
      isTab: true,
    },
    {
      type: "label",
      id: "746",
      fieldId: 31806,
      cols: 12,
      colSm: 12,
      colMd: 12,
      isMask: false,
      colLg: 12,
      width: "100%",
      name: "VCINFOACCOUNT",
      cssClass: "",
      webId: "",
      visible: false,
      required: false,
      page: 1,
      readonly: true,
      control: null,
      state: null,
      checked: null,
      error: null,
      isRelation: false,
      fieldRelation: null,
      isTab: true,
    },
    {
      label: "Статус оплаты",
      type: "label",
      id: "746",
      fieldId: 36524,
      cols: 4,
      colSm: 12,
      colMd: 12,
      isMask: false,
      colLg: 12,
      width: "100%",
      name: "SSTATEPAY",
      cssClass: "",
      webId: "",
      visible: false,
      required: false,
      page: 2,
      readonly: false,
      control: null,
      state: null,
      checked: null,
      error: null,
      isRelation: false,
      fieldRelation: null,
      isTab: true,
    },
    {
      value: "После оплаты чек будет направлен на телефон +7(985) 708-07-52 либо на e-mail egmen@yandex.ru",
      type: "label",
      structType: "string",
      id: "746",
      fieldId: 35998,
      cols: 12,
      colSm: 12,
      colMd: 12,
      isMask: false,
      colLg: 12,
      width: "100%",
      name: "PAY_CAPTION",
      cssClass: "",
      webId: "",
      visible: true,
      required: false,
      page: 1,
      readonly: false,
      control: null,
      state: null,
      checked: null,
      error: null,
      isRelation: false,
      fieldRelation: null,
      isTab: true,
    },
    {
      label: "С содержанием КИД (ключевого информационного документа) по страхованию АнтиКлеща ознакомлен.",
      value: false,
      type: "boolean",
      structType: "boolrus",
      id: "746",
      fieldId: 49344,
      cols: 8,
      colSm: 12,
      colMd: 12,
      isMask: false,
      colLg: 12,
      width: "80%",
      name: "BKID",
      cssClass: "",
      webId: "",
      visible: true,
      required: true,
      page: 1,
      readonly: false,
      control: null,
      state: null,
      checked: null,
      error: null,
      isRelation: false,
      fieldRelation: null,
      isTab: true,
    },
    {
      label: "Скачать КИД",
      type: "button",
      id: "746",
      fieldId: 49345,
      cols: 4,
      colSm: 12,
      colMd: 12,
      isMask: false,
      colLg: 12,
      width: "60%",
      name: "Item40010",
      cssClass: "btn-icon-download w-90",
      webId: "",
      visible: true,
      required: false,
      page: 1,
      readonly: false,
      control: null,
      state: null,
      checked: null,
      error: null,
      isRelation: false,
      fieldRelation: null,
      isTab: true,
    },
    {
      label: "Оплатить полис",
      type: "button",
      id: "746",
      fieldId: 31809,
      cols: 4,
      colSm: 12,
      colMd: 12,
      isMask: false,
      colLg: 12,
      width: "100%",
      name: "Item35682",
      cssClass: "btn-primary w-100 px-0",
      webId: "payBtn_mint_lk",
      visible: true,
      required: false,
      page: 1,
      readonly: false,
      control: null,
      state: null,
      checked: null,
      error: null,
      isRelation: false,
      fieldRelation: null,
      isTab: true,
    },
    {
      label: "Обновить статус оплаты",
      type: "button",
      id: "746",
      fieldId: 36525,
      cols: 4,
      colSm: 12,
      colMd: 12,
      isMask: false,
      colLg: 12,
      width: "100%",
      name: "Item36697",
      cssClass: "mt-3 mt-lg-0 d-block text-nowrap btn-secondary",
      webId: "",
      visible: false,
      required: false,
      page: 1,
      readonly: false,
      control: null,
      state: null,
      checked: null,
      error: null,
      isRelation: false,
      fieldRelation: null,
      isTab: true,
    },
    {
      label: "Уч № аддендума",
      value: 2598178146,
      type: "string",
      structType: "long",
      id: "746",
      fieldId: 31800,
      cols: 12,
      colSm: 12,
      colMd: 12,
      isMask: false,
      colLg: 12,
      width: "120%",
      name: "ID",
      cssClass: "",
      webId: "",
      visible: false,
      required: false,
      page: 0,
      readonly: false,
      control: null,
      state: null,
      checked: null,
      error: null,
      isRelation: false,
      fieldRelation: null,
      isTab: true,
    },
    {
      label: "Валюта",
      type: "double",
      id: "746",
      fieldId: 31803,
      cols: 4,
      colSm: 12,
      colMd: 12,
      isMask: false,
      colLg: 12,
      width: "120%",
      name: "IDCURRENCY",
      cssClass: "",
      webId: "",
      visible: false,
      required: false,
      page: 0,
      readonly: false,
      control: null,
      state: null,
      checked: null,
      error: null,
      isRelation: false,
      fieldRelation: null,
      isTab: true,
    },
    {
      value: "Не оплачен",
      type: "label",
      structType: "string",
      id: "746",
      fieldId: 60125,
      cols: 1,
      colSm: 12,
      colMd: 12,
      isMask: false,
      colLg: 12,
      width: "100%",
      name: "SSTATENAME",
      cssClass: "",
      webId: "",
      visible: false,
      required: false,
      page: 0,
      readonly: false,
      control: null,
      state: null,
      checked: null,
      error: null,
      isRelation: false,
      fieldRelation: null,
      isTab: true,
    },
    {
      value: false,
      type: "label",
      structType: "boolean",
      id: "746",
      fieldId: 60124,
      cols: 1,
      colSm: 12,
      colMd: 12,
      isMask: false,
      colLg: 12,
      width: "100%",
      name: "LPROMOCODE",
      cssClass: "",
      webId: "",
      visible: false,
      required: false,
      page: 0,
      readonly: false,
      control: null,
      state: null,
      checked: null,
      error: null,
      isRelation: false,
      fieldRelation: null,
      isTab: true,
    },
    {
      label: "со скидкой",
      value: "300",
      type: "label",
      structType: "string",
      id: "746",
      fieldId: 60122,
      cols: 1,
      colSm: 12,
      colMd: 12,
      isMask: false,
      colLg: 12,
      width: "100%",
      name: "NDISCOUNTPREMIUM",
      cssClass: "",
      webId: "",
      visible: false,
      required: false,
      page: 0,
      readonly: false,
      control: null,
      state: null,
      checked: null,
      error: null,
      isRelation: false,
      fieldRelation: null,
      isTab: true,
    },
    {
      label: "первоначальная цена",
      value: "301",
      type: "label",
      structType: "string",
      id: "746",
      fieldId: 60123,
      cols: 1,
      colSm: 12,
      colMd: 12,
      isMask: false,
      colLg: 12,
      width: "100%",
      name: "NPREMIUM",
      cssClass: "",
      webId: "",
      visible: false,
      required: false,
      page: 0,
      readonly: false,
      control: null,
      state: null,
      checked: null,
      error: null,
      isRelation: false,
      fieldRelation: null,
      isTab: true,
    },
    {
      label: "<style>.mt-4.buttons.row {display:none}</style>",
      type: "empty",
      id: "746",
      fieldId: 49334,
      cols: 15,
      colSm: 15,
      colMd: 12,
      isMask: false,
      colLg: 12,
      width: "100%",
      name: "style",
      cssClass: "",
      webId: "",
      visible: true,
      required: false,
      page: 0,
      readonly: false,
      control: null,
      state: null,
      checked: null,
      error: null,
      isRelation: false,
      fieldRelation: null,
      isTab: true,
    },
  ];

  it("Check discount price label", async () => {
    const wrapper = mount(PriceComponent, {
      propsData,
      methods: {
        isFieldExists(name, data = undefined) {
          return Boolean(this.getField(name, data));
        },
        getField(name) {
          return formData.find((item) => item.name === name);
        },
        getFieldValue(name) {
          return this.getField(name) ? this.getField(name).value : "";
        },
        getFieldLabel(name) {
          return this.getField(name) ? this.getField(name).label : "Стоимость полиса";
        },
        getVisible(name) {
          return this.getField(name) ? this.getField(name).visible : "";
        },
        label(name) {
          return this.getField(name) ? this.getField(name)?.label : "Стоимость полиса";
        },
      },
      computed: {
        formData() {
          return formData;
        },
      },
    });

    await wrapper.vm.$nextTick();

    expect(wrapper.contains(".use_discount")).toBeTruthy();
  });
});
