export default {
  wizardRels: [
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "10",
    "11",
    "12",
    "13",
  ],
  wizardCursor: [
    {
      MENUCUR: [
        {
          LDELETE: false,
          IDADMMENUTYPE: 9,
          SNAME: "Тип расчета",
          LMODALFORMSTYLE: false,
          NONETOMANY: 0,
          LNEW: false,
          LEDIT: true,
          NORDER: 1,
          LNOTCARD: false,
          ACTIONSCUR: [],
          ID: 12798,
          LFIRSTLOADRECORD: true,
          IDITEM: 1037,
          ONETOMANYCUR: [],
          IDPARENT: 0,
          LPRINT: false,
          LNEWRECORDMETHOD: true,
        },
      ],
      SNAME: "Тип расчета",
      NORDER: 1,
      LOPENLIST: false,
      ID: 4528,
      NITEMPARENTMENU: 1036,
      NITEM: 1037,
      IDADMMODULE: 55,
    },
    {
      MENUCUR: [
        {
          LDELETE: false,
          IDADMMENUTYPE: 9,
          SNAME: "Данные об авто",
          LMODALFORMSTYLE: false,
          NONETOMANY: 0,
          LNEW: true,
          LEDIT: true,
          NORDER: 2,
          LNOTCARD: false,
          ACTIONSCUR: [],
          ID: 12799,
          LFIRSTLOADRECORD: true,
          IDITEM: 1039,
          ONETOMANYCUR: [],
          IDPARENT: 0,
          LPRINT: false,
          LNEWRECORDMETHOD: true,
        },
      ],
      SNAME: "Данные об авто",
      NORDER: 2,
      LOPENLIST: false,
      ID: 4530,
      NITEMPARENTMENU: 1036,
      NITEM: 1039,
      IDADMMODULE: 55,
    },
    {
      MENUCUR: [
        {
          LDELETE: false,
          IDADMMENUTYPE: 9,
          SNAME: "Расчет",
          LMODALFORMSTYLE: false,
          NONETOMANY: 0,
          LNEW: true,
          LEDIT: true,
          NORDER: 3,
          LNOTCARD: false,
          ACTIONSCUR: [],
          ID: 12800,
          LFIRSTLOADRECORD: true,
          IDITEM: 1040,
          ONETOMANYCUR: [],
          IDPARENT: 0,
          LPRINT: false,
          LNEWRECORDMETHOD: false,
        },
      ],
      SNAME: "Расчет",
      NORDER: 3,
      LOPENLIST: false,
      ID: 4526,
      NITEMPARENTMENU: 1036,
      NITEM: 1040,
      IDADMMODULE: 55,
    },
    {
      MENUCUR: [
        {
          LDELETE: false,
          IDADMMENUTYPE: 9,
          SNAME: "Личные данные",
          LMODALFORMSTYLE: false,
          NONETOMANY: 0,
          LNEW: false,
          LEDIT: true,
          NORDER: 4,
          LNOTCARD: false,
          ACTIONSCUR: [
            {
              LUSEINCARD: true,
              LIDLIST: false,
              LSELECTDEFAULT: false,
              LINBUTTONS: false,
              NITEM: 1041,
              LCREATEBUTTON: false,
              LCHECKACCESS: false,
              LFROMDATASET: true,
              LINLIST: false,
              LOUTPARAM: false,
              LWITHCOMMIT: false,
              ID: 45576,
              LCURWINDOW: true,
              LMULTISELECT: false,
              SCONST: "Mobile.ClientUtils.SendEmail",
              SNAME: "Получить код",
              LFREEZONE: false,
              LREQUESTCODE: false,
              LCLOSEAFTER: false,
              LINACTIONS: true,
              LREFRESH: false,
              REL: "FB79C94372FD7F0530D8A6E43BDA9022",
              SFIELD: "id",
              NTYPE: 4,
              LHIDEDLG: true,
              IDADMMODULE: 55,
              LNEEDPARAM: false,
              LHIDEINLIST: false,
              LTOOLBAR: false,
            },
          ],
          ID: 12801,
          LFIRSTLOADRECORD: true,
          IDITEM: 1041,
          ONETOMANYCUR: [],
          IDPARENT: 0,
          LPRINT: false,
          LNEWRECORDMETHOD: false,
        },
      ],
      SNAME: "Личные данные",
      NORDER: 4,
      LOPENLIST: false,
      ID: 4529,
      NITEMPARENTMENU: 1036,
      NITEM: 1041,
      IDADMMODULE: 55,
    },
    {
      MENUCUR: [
        {
          LDELETE: false,
          IDADMMENUTYPE: 9,
          SNAME: "Данные о ТС",
          LMODALFORMSTYLE: false,
          NONETOMANY: 0,
          LNEW: true,
          LEDIT: true,
          NORDER: 5,
          LNOTCARD: false,
          ACTIONSCUR: [],
          ID: 12805,
          LFIRSTLOADRECORD: true,
          IDITEM: 1064,
          ONETOMANYCUR: [],
          IDPARENT: 0,
          LPRINT: false,
          LNEWRECORDMETHOD: true,
        },
      ],
      SNAME: "Сведения о ТС",
      NORDER: 5,
      LOPENLIST: false,
      ID: 4527,
      NITEMPARENTMENU: 1036,
      NITEM: 1064,
      IDADMMODULE: 55,
    },
    {
      MENUCUR: [
        {
          LDELETE: false,
          IDADMMENUTYPE: 9,
          SNAME: "Доп сведения о ТС",
          LMODALFORMSTYLE: false,
          NONETOMANY: 0,
          LNEW: true,
          LEDIT: true,
          NORDER: 6,
          LNOTCARD: false,
          ACTIONSCUR: [],
          ID: 12806,
          LFIRSTLOADRECORD: true,
          IDITEM: 1065,
          ONETOMANYCUR: [],
          IDPARENT: 0,
          LPRINT: false,
          LNEWRECORDMETHOD: true,
        },
      ],
      SNAME: "Доп сведения о ТС",
      NORDER: 6,
      LOPENLIST: false,
      ID: 4538,
      NITEMPARENTMENU: 1036,
      NITEM: 1065,
      IDADMMODULE: 55,
    },
    {
      MENUCUR: [
        {
          LDELETE: false,
          IDADMMENUTYPE: 9,
          SNAME: "Документы ТС",
          LMODALFORMSTYLE: false,
          NONETOMANY: 0,
          LNEW: true,
          LEDIT: true,
          NORDER: 7,
          LNOTCARD: false,
          ACTIONSCUR: [],
          ID: 12807,
          LFIRSTLOADRECORD: true,
          IDITEM: 1066,
          ONETOMANYCUR: [],
          IDPARENT: 0,
          LPRINT: false,
          LNEWRECORDMETHOD: true,
        },
      ],
      SNAME: "Документы ТС",
      NORDER: 7,
      LOPENLIST: false,
      ID: 4531,
      NITEMPARENTMENU: 1036,
      NITEM: 1066,
      IDADMMODULE: 55,
    },
    {
      MENUCUR: [
        {
          LDELETE: false,
          IDADMMENUTYPE: 9,
          SNAME: "Водители",
          LMODALFORMSTYLE: false,
          NONETOMANY: 0,
          LNEW: true,
          LEDIT: true,
          NORDER: 8,
          LNOTCARD: false,
          ACTIONSCUR: [],
          ID: 12808,
          LFIRSTLOADRECORD: true,
          IDITEM: 1068,
          ONETOMANYCUR: [],
          IDPARENT: 0,
          LPRINT: false,
          LNEWRECORDMETHOD: true,
        },
      ],
      SNAME: "Водители",
      NORDER: 8,
      LOPENLIST: false,
      ID: 4532,
      NITEMPARENTMENU: 1036,
      NITEM: 1068,
      IDADMMODULE: 55,
    },
    {
      MENUCUR: [
        {
          LDELETE: false,
          IDADMMENUTYPE: 9,
          SNAME: "Параметры полиса",
          LMODALFORMSTYLE: false,
          NONETOMANY: 0,
          LNEW: true,
          LEDIT: true,
          NORDER: 9,
          LNOTCARD: false,
          ACTIONSCUR: [],
          ID: 12810,
          LFIRSTLOADRECORD: true,
          IDITEM: 1069,
          ONETOMANYCUR: [],
          IDPARENT: 0,
          LPRINT: false,
          LNEWRECORDMETHOD: true,
        },
      ],
      SNAME: "Параметры полиса",
      NORDER: 9,
      LOPENLIST: false,
      ID: 4533,
      NITEMPARENTMENU: 1036,
      NITEM: 1069,
      IDADMMODULE: 55,
    },
    {
      MENUCUR: [
        {
          LDELETE: false,
          IDADMMENUTYPE: 9,
          SNAME: "Точный расчет",
          LMODALFORMSTYLE: false,
          NONETOMANY: 0,
          LNEW: true,
          LEDIT: true,
          NORDER: 10,
          LNOTCARD: false,
          ACTIONSCUR: [],
          ID: 12811,
          LFIRSTLOADRECORD: true,
          IDITEM: 1070,
          ONETOMANYCUR: [],
          IDPARENT: 0,
          LPRINT: false,
          LNEWRECORDMETHOD: false,
        },
      ],
      SNAME: "Точный расчет",
      NORDER: 10,
      LOPENLIST: false,
      ID: 4534,
      NITEMPARENTMENU: 1036,
      NITEM: 1070,
      IDADMMODULE: 55,
    },
    {
      MENUCUR: [
        {
          LDELETE: false,
          IDADMMENUTYPE: 9,
          SNAME: "Сканы документов",
          LMODALFORMSTYLE: false,
          NONETOMANY: 0,
          LNEW: false,
          LEDIT: true,
          NORDER: 11,
          LNOTCARD: false,
          ACTIONSCUR: [],
          ID: 12802,
          LFIRSTLOADRECORD: true,
          IDITEM: 1048,
          ONETOMANYCUR: [],
          IDPARENT: 0,
          LPRINT: false,
          LNEWRECORDMETHOD: false,
        },
      ],
      SNAME: "Сканы документов",
      NORDER: 11,
      LOPENLIST: false,
      ID: 4535,
      NITEMPARENTMENU: 1036,
      NITEM: 1048,
      IDADMMODULE: 55,
    },
    {
      MENUCUR: [
        {
          LDELETE: false,
          IDADMMENUTYPE: 9,
          SNAME: "Осмотр",
          LMODALFORMSTYLE: false,
          NONETOMANY: 0,
          LNEW: false,
          LEDIT: true,
          NORDER: 12,
          LNOTCARD: false,
          ACTIONSCUR: [
            {
              LUSEINCARD: true,
              LIDLIST: false,
              LSELECTDEFAULT: false,
              LINBUTTONS: false,
              NITEM: 1049,
              LCREATEBUTTON: false,
              LCHECKACCESS: false,
              LFROMDATASET: false,
              LINLIST: false,
              LOUTPARAM: true,
              LWITHCOMMIT: false,
              ID: 45577,
              LCURWINDOW: true,
              LMULTISELECT: false,
              SCONST: "v4.cascoutils_web.OpenIns",
              SNAME: "Изменить данные заявки",
              LFREEZONE: false,
              LREQUESTCODE: false,
              LCLOSEAFTER: false,
              LINACTIONS: true,
              LREFRESH: true,
              REL: "B834BA52B5F73A020FBDE952B821DF4B",
              SFIELD: "id",
              NTYPE: 4,
              LHIDEDLG: true,
              IDADMMODULE: 55,
              LNEEDPARAM: false,
              LHIDEINLIST: true,
              LTOOLBAR: false,
            },
            {
              LUSEINCARD: true,
              LIDLIST: false,
              LSELECTDEFAULT: false,
              LINBUTTONS: false,
              NITEM: 1049,
              LCREATEBUTTON: false,
              LCHECKACCESS: false,
              LFROMDATASET: false,
              LINLIST: false,
              LOUTPARAM: true,
              LWITHCOMMIT: false,
              ID: 45578,
              LCURWINDOW: true,
              LMULTISELECT: false,
              SCONST: "v4.cascoutils_web.UpdateIns",
              SNAME: "Принять",
              LFREEZONE: false,
              LREQUESTCODE: false,
              LCLOSEAFTER: false,
              LINACTIONS: true,
              LREFRESH: true,
              REL: "E372EBAA89ED7A00C826A8EA7E98732C",
              SFIELD: "id",
              NTYPE: 4,
              LHIDEDLG: true,
              IDADMMODULE: 55,
              LNEEDPARAM: false,
              LHIDEINLIST: true,
              LTOOLBAR: false,
            },
          ],
          ID: 12803,
          LFIRSTLOADRECORD: true,
          IDITEM: 1049,
          ONETOMANYCUR: [],
          IDPARENT: 0,
          LPRINT: false,
          LNEWRECORDMETHOD: false,
        },
      ],
      SNAME: "Осмотр",
      NORDER: 12,
      LOPENLIST: false,
      ID: 4536,
      NITEMPARENTMENU: 1036,
      NITEM: 1049,
      IDADMMODULE: 55,
    },
    {
      MENUCUR: [
        {
          LDELETE: false,
          IDADMMENUTYPE: 9,
          SNAME: "Оплата",
          LMODALFORMSTYLE: false,
          NONETOMANY: 0,
          LNEW: true,
          LEDIT: true,
          NORDER: 13,
          LNOTCARD: false,
          ACTIONSCUR: [
            {
              LUSEINCARD: true,
              LIDLIST: false,
              LSELECTDEFAULT: false,
              LINBUTTONS: false,
              NITEM: 1085,
              LCREATEBUTTON: false,
              LCHECKACCESS: false,
              LFROMDATASET: false,
              LINLIST: false,
              LOUTPARAM: true,
              LWITHCOMMIT: false,
              ID: 45834,
              LCURWINDOW: false,
              LMULTISELECT: false,
              SCONST: "v4.cascoutils_web.OpenPrintKidNSLinkButton",
              SNAME: "Скачать КИД НС",
              LFREEZONE: false,
              LREQUESTCODE: false,
              LCLOSEAFTER: false,
              LINACTIONS: true,
              LREFRESH: false,
              REL: "0F1424F50FD7C6A9D7854C0271371104",
              SFIELD: "id",
              NTYPE: 4,
              LHIDEDLG: true,
              IDADMMODULE: 55,
              LNEEDPARAM: false,
              LHIDEINLIST: false,
              LTOOLBAR: false,
            },
            {
              LUSEINCARD: true,
              LIDLIST: false,
              LSELECTDEFAULT: false,
              LINBUTTONS: false,
              NITEM: 1085,
              LCREATEBUTTON: false,
              LCHECKACCESS: false,
              LFROMDATASET: false,
              LINLIST: false,
              LOUTPARAM: true,
              LWITHCOMMIT: false,
              ID: 45837,
              LCURWINDOW: false,
              LMULTISELECT: false,
              SCONST: "v4.cascoutils_web.OpenPrintKidRAPLinkButton",
              SNAME: "Скачать КИД РАП",
              LFREEZONE: false,
              LREQUESTCODE: false,
              LCLOSEAFTER: false,
              LINACTIONS: true,
              LREFRESH: false,
              REL: "E5F70412556368D1C8E212E6DEF2ECBC",
              SFIELD: "id",
              NTYPE: 4,
              LHIDEDLG: true,
              IDADMMODULE: 55,
              LNEEDPARAM: false,
              LHIDEINLIST: false,
              LTOOLBAR: false,
            },
            {
              LUSEINCARD: true,
              LIDLIST: false,
              LSELECTDEFAULT: false,
              LINBUTTONS: false,
              NITEM: 1085,
              LCREATEBUTTON: false,
              LCHECKACCESS: false,
              LFROMDATASET: false,
              LINLIST: false,
              LOUTPARAM: true,
              LWITHCOMMIT: false,
              ID: 45833,
              LCURWINDOW: false,
              LMULTISELECT: false,
              SCONST: "v4.cascoutils_web.GetLinkRules",
              SNAME: "Правила страхования",
              LFREEZONE: false,
              LREQUESTCODE: false,
              LCLOSEAFTER: false,
              LINACTIONS: true,
              LREFRESH: false,
              REL: "5B0A7D6CFD3ECBDD1DC036A5BAE99225",
              SFIELD: "id",
              NTYPE: 4,
              LHIDEDLG: true,
              IDADMMODULE: 55,
              LNEEDPARAM: false,
              LHIDEINLIST: false,
              LTOOLBAR: false,
            },
            {
              LUSEINCARD: true,
              LIDLIST: false,
              LSELECTDEFAULT: false,
              LINBUTTONS: false,
              NITEM: 1085,
              LCREATEBUTTON: false,
              LCHECKACCESS: false,
              LFROMDATASET: false,
              LINLIST: false,
              LOUTPARAM: true,
              LWITHCOMMIT: false,
              ID: 45579,
              LCURWINDOW: false,
              LMULTISELECT: false,
              SCONST: "v4.cascoutils_web.OpenPrintKidLinkButton",
              SNAME: "Скачать КИД",
              LFREEZONE: false,
              LREQUESTCODE: false,
              LCLOSEAFTER: false,
              LINACTIONS: true,
              LREFRESH: false,
              REL: "AC2C8D09F680639348034D0C06229DC6",
              SFIELD: "id",
              NTYPE: 4,
              LHIDEDLG: true,
              IDADMMODULE: 55,
              LNEEDPARAM: false,
              LHIDEINLIST: false,
              LTOOLBAR: false,
            },
            {
              LUSEINCARD: true,
              LIDLIST: false,
              LSELECTDEFAULT: false,
              LINBUTTONS: false,
              NITEM: 1085,
              LCREATEBUTTON: false,
              LCHECKACCESS: false,
              LFROMDATASET: false,
              LINLIST: false,
              LOUTPARAM: true,
              LWITHCOMMIT: false,
              ID: 45580,
              LCURWINDOW: true,
              LMULTISELECT: false,
              SCONST: "v4.cascoutils_web.OpenExactCalc",
              SNAME: "Внести изменения",
              LFREEZONE: false,
              LREQUESTCODE: false,
              LCLOSEAFTER: false,
              LINACTIONS: true,
              LREFRESH: false,
              REL: "A92966E7F930CAAD68F389CC95A50AB9",
              SFIELD: "id",
              NTYPE: 4,
              LHIDEDLG: true,
              IDADMMODULE: 55,
              LNEEDPARAM: false,
              LHIDEINLIST: true,
              LTOOLBAR: false,
            },
            {
              LUSEINCARD: true,
              LIDLIST: false,
              LSELECTDEFAULT: false,
              LINBUTTONS: false,
              NITEM: 1085,
              LCREATEBUTTON: false,
              LCHECKACCESS: false,
              LFROMDATASET: false,
              LINLIST: false,
              LOUTPARAM: false,
              LWITHCOMMIT: false,
              ID: 45581,
              LCURWINDOW: false,
              LMULTISELECT: false,
              SCONST: "v4.cascoutils_web.Refresh",
              SNAME: "Обновить статус оплаты",
              LFREEZONE: false,
              LREQUESTCODE: false,
              LCLOSEAFTER: false,
              LINACTIONS: true,
              LREFRESH: true,
              REL: "454F5B84D80ADF63C3A6318843F43786",
              SFIELD: "id",
              NTYPE: 4,
              LHIDEDLG: true,
              IDADMMODULE: 55,
              LNEEDPARAM: false,
              LHIDEINLIST: false,
              LTOOLBAR: false,
            },
            {
              LUSEINCARD: true,
              LIDLIST: false,
              LSELECTDEFAULT: false,
              LINBUTTONS: false,
              NITEM: 1085,
              LCREATEBUTTON: false,
              LCHECKACCESS: false,
              LFROMDATASET: false,
              LINLIST: false,
              LOUTPARAM: true,
              LWITHCOMMIT: false,
              ID: 45582,
              LCURWINDOW: false,
              LMULTISELECT: false,
              SCONST: "v4.cascoutils_web.OpenPrintLinkButton",
              SNAME: "Распечатать проект полиса",
              LFREEZONE: false,
              LREQUESTCODE: false,
              LCLOSEAFTER: false,
              LINACTIONS: true,
              LREFRESH: false,
              REL: "5EB5DF6FECFDCA8FB3A658B35F598740",
              SFIELD: "id",
              NTYPE: 4,
              LHIDEDLG: true,
              IDADMMODULE: 55,
              LNEEDPARAM: false,
              LHIDEINLIST: false,
              LTOOLBAR: false,
            },
            {
              LUSEINCARD: true,
              LIDLIST: false,
              LSELECTDEFAULT: false,
              LINBUTTONS: false,
              NITEM: 1085,
              LCREATEBUTTON: false,
              LCHECKACCESS: false,
              LFROMDATASET: false,
              LINLIST: false,
              LOUTPARAM: true,
              LWITHCOMMIT: false,
              ID: 45583,
              LCURWINDOW: true,
              LMULTISELECT: false,
              SCONST: "v4.cascoutils_web.OpenPayLinkButton",
              SNAME: "Оплатить полис",
              LFREEZONE: false,
              LREQUESTCODE: false,
              LCLOSEAFTER: false,
              LINACTIONS: true,
              LREFRESH: true,
              REL: "EAA1604FA40072C03076500D6F832B7C",
              SFIELD: "id",
              NTYPE: 4,
              LHIDEDLG: true,
              IDADMMODULE: 55,
              LNEEDPARAM: false,
              LHIDEINLIST: false,
              LTOOLBAR: false,
            },
          ],
          ID: 12813,
          LFIRSTLOADRECORD: true,
          IDITEM: 1085,
          ONETOMANYCUR: [],
          IDPARENT: 0,
          LPRINT: false,
          LNEWRECORDMETHOD: false,
        },
      ],
      SNAME: "Оплата",
      NORDER: 13,
      LOPENLIST: false,
      ID: 4537,
      NITEMPARENTMENU: 1036,
      NITEM: 1085,
      IDADMMODULE: 55,
    },
  ],
  wizardIDCARDS: [1037, 1039, 1040, 1041, 4527, 4538, 4531, 4532, 4533, 4534, 4535, 4536, 4537],
  wizardNavigation: {
    back: {},
    current: {
      REL: "2",
      IDCARD: 1041,
    },
    next: {},
  },
}
