import { isCaptchaNeeded } from "./isCaptchaNeeded";

describe("Проверка капчи", () => {
  it("Капча видима", () => {
    const TEST_DATA = [
      {
        label: "Количество застрахованных",
        value: 2,
        type: "combobox",
        structType: "long",
        id: "666",
        fieldId: 37108,
        cols: 3,
        colSm: 12,
        colMd: 12,
        colLg: 3,
        width: "100%",
        name: "SCOUNT",
        cssClass: "",
        visible: true,
        required: true,
        page: 0,
        readonly: false,
        control: null,
        state: true,
        checked: true,
        error: null,
        placeholder: "Выберите из списка",
        isRelation: true,
        fieldRelation: null,
        isTab: false,
        options: [
          { SNAME: 1, ID: 1, text: "1", value: 1 },
          { SNAME: 2, ID: 2, text: "2", value: 2 },
          { SNAME: 3, ID: 3, text: "3", value: 3 },
          { SNAME: 4, ID: 4, text: "4", value: 4 },
          { SNAME: 5, ID: 5, text: "5", value: 5 },
        ],
      },
      {
        label: "Капча",
        value: "6LcR59kUAAAAAN9gdxm2TWPCTey73RTAKGIOkTTV",
        type: "GoogleCaptcha",
        structType: "string",
        id: "666",
        fieldId: 37110,
        cols: 1,
        colSm: 12,
        colMd: 12,
        colLg: 12,
        width: "100%",
        name: "SCAPTCHA",
        cssClass: "mt-3",
        visible: true,
        required: true,
        page: 0,
        readonly: false,
        control: null,
        state: true,
        checked: true,
        error: null,
        isRelation: false,
        fieldRelation: null,
        isTab: false,
      },
    ];
    const isVisible = isCaptchaNeeded(TEST_DATA);
    expect(isVisible).toBe(true);
  });

  it("Капча невидима", () => {
    const TEST_DATA = [
      {
        label: "Количество застрахованных",
        value: 2,
        type: "combobox",
        structType: "long",
        id: "666",
        fieldId: 37108,
        cols: 3,
        colSm: 12,
        colMd: 12,
        colLg: 3,
        width: "100%",
        name: "SCOUNT",
        cssClass: "",
        visible: true,
        required: true,
        page: 0,
        readonly: false,
        control: null,
        state: true,
        checked: true,
        error: null,
        placeholder: "Выберите из списка",
        isRelation: true,
        fieldRelation: null,
        isTab: false,
        options: [
          { SNAME: 1, ID: 1, text: "1", value: 1 },
          { SNAME: 2, ID: 2, text: "2", value: 2 },
          { SNAME: 3, ID: 3, text: "3", value: 3 },
          { SNAME: 4, ID: 4, text: "4", value: 4 },
          { SNAME: 5, ID: 5, text: "5", value: 5 },
        ],
      },
      {
        label: "Капча",
        value: "6LcR59kUAAAAAN9gdxm2TWPCTey73RTAKGIOkTTV",
        type: "GoogleCaptcha",
        structType: "string",
        id: "666",
        fieldId: 37110,
        cols: 1,
        colSm: 12,
        colMd: 12,
        colLg: 12,
        width: "100%",
        name: "SCAPTCHA",
        cssClass: "mt-3",
        visible: false,
        required: true,
        page: 0,
        readonly: false,
        control: null,
        state: true,
        checked: true,
        error: null,
        isRelation: false,
        fieldRelation: null,
        isTab: false,
      },
    ];
    const isVisible = isCaptchaNeeded(TEST_DATA);
    expect(isVisible).toBe(false);
  });

  it("Капчи нет", () => {
    const TEST_DATA = [
      {
        label: "Количество застрахованных",
        value: 2,
        type: "combobox",
        structType: "long",
        id: "666",
        fieldId: 37108,
        cols: 3,
        colSm: 12,
        colMd: 12,
        colLg: 3,
        width: "100%",
        name: "SCOUNT",
        cssClass: "",
        visible: true,
        required: true,
        page: 0,
        readonly: false,
        control: null,
        state: true,
        checked: true,
        error: null,
        placeholder: "Выберите из списка",
        isRelation: true,
        fieldRelation: null,
        isTab: false,
        options: [
          { SNAME: 1, ID: 1, text: "1", value: 1 },
          { SNAME: 2, ID: 2, text: "2", value: 2 },
          { SNAME: 3, ID: 3, text: "3", value: 3 },
          { SNAME: 4, ID: 4, text: "4", value: 4 },
          { SNAME: 5, ID: 5, text: "5", value: 5 },
        ],
      },
    ];
    const isVisible = isCaptchaNeeded(TEST_DATA);
    expect(isVisible).toBe(false);
  });
});
