export const dataProps = {
  checked: true,
  colLg: 13,
  colMd: 12,
  colSm: 12,
  cols: 3,
  control: null,
  error: null,
  fieldId: 37106,
  fieldRelation: null,
  id: "765",
  isRelation: true,
  isTab: false,
  label: "Серия",
  cssClass: "",
  name: "SSERIES",
  options: [
    {
      ID: 1,
      SNAME: "ААА",
      text: "ААА",
      value: 1,
    },
  ],
  page: 0,
  placeholder: "Выберите серию",
  readonly: false,
  required: true,
  state: true,
  structType: "string",
  type: "customCombobox",
  value: 1,
  visible: true,
  webId: "",
  width: "100%",
  disabled: false,
  edit: true,
  loading: false,
  params: undefined,
  profileFullness: undefined,
  store: undefined,
};
