export const dataProps = {
  label: "Электронная почта",
  type: "emailChange",
  structType: "string",
  id: "718",
  fieldId: 35724,
  cols: 12,
  colSm: 12,
  colMd: 12,
  colLg: 12,
  width: "100%",
  name: "SEMAILNEW",
  cssClass: "mt-3",
  webId: "",
  visible: true,
  required: true,
  page: 0,
  readonly: false,
  control: null,
  state: true,
  checked: true,
  error: null,
  isRelation: false,
  fieldRelation: null,
  isTab: true,
  value: "hhh@mail.ru",
};

export const getSMSCodeComponent = {
  checked: null,
  colLg: 12,
  colMd: 12,
  colSm: 12,
  cols: 4,
  control: null,
  cssClass: "",
  error: null,
  fieldId: 63058,
  fieldRelation: null,
  id: "999",
  isMask: false,
  isRelation: false,
  isTab: true,
  label: "Код подтверждения",
  name: "SCODEFIELD",
  page: 4,
  readonly: false,
  required: true,
  state: null,
  type: "string",
  visible: false,
  webId: "",
  width: "100%",
};
export const params = {
  ns: "data_card",
};
