export const dataProps = {
  checked: null,
  colLg: 12,
  colMd: 12,
  colSm: 12,
  cols: 6,
  control: null,
  cssClass: "",
  dic: "IDDATE",
  error: null,
  fieldId: 51221,
  fieldRelation: "IDINDEP_PSO_OFF",
  id: "994",
  isMask: false,
  isRelation: true,
  isTab: true,
  label: "Дата осмотра",
  name: "FKIDDATE",
  options: [],
  page: 0,
  readonly: false,
  required: true,
  state: null,
  type: "enum",
  value: {},
  visible: true,
  webId: "",
  width: "100%",
};

export const params = {
  idModule: "55",
  idParent: "0",
  idItem: "994",
  idCard: "3410",
  idRel: "561726822DB388DC5D2792CD143CBBF7",
  query: { ref: "/cabinet/55/0/946/3410/A9C5522BC9A2F86589DCE0E10E858B76" },
};
export const fetchForm = {
  errors: [],
  data: [
    {
      label: "IDECLAIM",
      value: 3410,
      id: "994",
      type: "double",
      maxlength: 4,
      name: "IDECLAIM",
      visible: true,
      required: false,
      readonly: false,
      control: null,
      state: null,
      isTab: false,
    },
    {
      label: "STSADDRESS",
      id: "994",
      type: "text",
      maxlength: 400,
      name: "STSADDRESS",
      visible: true,
      required: false,
      readonly: false,
      control: null,
      state: null,
      isTab: false,
    },
  ],
  metaData: {
    data: [
      {
        label: "IDECLAIM",
        value: 3410,
        type: "string",
        structType: "double",
        id: "994",
        fieldId: 51284,
        cols: 1,
        colSm: 12,
        colMd: 12,
        isMask: false,
        colLg: 12,
        width: "100%",
        name: "IDECLAIM",
        cssClass: "",
        webId: "",
        visible: false,
        required: false,
        page: 0,
        readonly: false,
        control: null,
        state: null,
        checked: null,
        error: null,
        isRelation: false,
        fieldRelation: null,
        isTab: true,
      },
      {
        label: "Запись на осмотр ТС",
        type: "splitter",
        id: "994",
        fieldId: 51216,
        cols: 12,
        colSm: 12,
        colMd: 12,
        isMask: false,
        colLg: 12,
        width: "100%",
        name: "ITEM_Devider_1",
        cssClass: "",
        webId: "",
        visible: true,
        required: false,
        page: 0,
        readonly: false,
        control: null,
        state: null,
        checked: null,
        error: null,
        isRelation: false,
        fieldRelation: null,
        isTab: true,
      },
      {
        label: "Адрес осмотра",
        type: "string",
        structType: "string",
        id: "994",
        fieldId: 51218,
        cols: 12,
        colSm: 12,
        colMd: 12,
        isMask: false,
        colLg: 12,
        width: "100%",
        name: "STSADDRESS",
        cssClass: "",
        webId: "",
        visible: false,
        required: false,
        page: 0,
        readonly: true,
        control: null,
        state: null,
        checked: null,
        error: null,
        isRelation: false,
        fieldRelation: null,
        isTab: true,
      },
      {
        label: "Точка осмотра",
        value: {},
        type: "enum",
        id: "994",
        fieldId: 51220,
        cols: 12,
        colSm: 12,
        colMd: 12,
        isMask: false,
        colLg: 12,
        width: "100%",
        name: "FKIDINDEP_PSO_OFF",
        cssClass: "",
        webId: "",
        visible: true,
        required: false,
        page: 0,
        readonly: false,
        control: null,
        state: null,
        checked: null,
        error: null,
        isRelation: false,
        fieldRelation: null,
        isTab: true,
        dic: "IDINDEP_PSO_OFF",
        options: null,
      },
      {
        label: "Дата осмотра",
        value: {},
        type: "enum",
        id: "994",
        fieldId: 51221,
        cols: 6,
        colSm: 12,
        colMd: 12,
        isMask: false,
        colLg: 12,
        width: "100%",
        name: "FKIDDATE",
        cssClass: "",
        webId: "",
        visible: true,
        required: false,
        page: 0,
        readonly: false,
        control: null,
        state: null,
        checked: null,
        error: null,
        isRelation: true,
        fieldRelation: "IDINDEP_PSO_OFF",
        isTab: true,
        dic: "IDDATE",
        options: null,
      },
      {
        label: "Дата осмотра",
        value: {},
        type: "enum",
        id: "994",
        fieldId: 51223,
        cols: 6,
        colSm: 12,
        colMd: 12,
        isMask: false,
        colLg: 12,
        width: "100%",
        name: "FKIDDATE_PLACE2",
        cssClass: "",
        webId: "",
        visible: false,
        required: false,
        page: 0,
        readonly: false,
        control: null,
        state: null,
        checked: null,
        error: null,
        isRelation: false,
        fieldRelation: null,
        isTab: true,
        dic: "IDDATE_PLACE2",
        options: null,
      },
      {
        label: "Ничего не подходит, свяжитесь со мной",
        type: "button",
        id: "994",
        fieldId: 51225,
        cols: 6,
        colSm: 12,
        colMd: 12,
        isMask: false,
        colLg: 12,
        width: "100%",
        name: "Item40786",
        cssClass: "mt-btn-gray w-100 btn-gray",
        webId: "",
        visible: true,
        required: false,
        page: 0,
        readonly: false,
        control: null,
        state: null,
        checked: null,
        error: null,
        isRelation: false,
        fieldRelation: null,
        isTab: true,
      },
      {
        label: "Сохранить",
        type: "button",
        id: "994",
        fieldId: 51226,
        cols: 3,
        colSm: 12,
        colMd: 12,
        isMask: false,
        colLg: 12,
        width: "100%",
        name: "Item40785",
        cssClass: "btn-primary mt-3 w-100 d-table mt-lg-4",
        webId: "",
        visible: true,
        required: false,
        page: 0,
        readonly: false,
        control: null,
        state: null,
        checked: null,
        error: null,
        isRelation: false,
        fieldRelation: null,
        isTab: true,
      },
      {
        label: "Отменить",
        type: "button",
        id: "994",
        fieldId: 51227,
        cols: 3,
        colSm: 12,
        colMd: 12,
        isMask: false,
        colLg: 12,
        width: "100%",
        name: "Item40787",
        cssClass: "btn-secondary mt-3  w-100 d-table mt-lg-4",
        webId: "",
        visible: true,
        required: false,
        page: 0,
        readonly: false,
        control: null,
        state: null,
        checked: null,
        error: null,
        isRelation: false,
        fieldRelation: null,
        isTab: true,
      },
    ],
    defaultValues: {},
    captions: '"1";',
    btnSave: false,
    btnCancel: false,
    readonly: false,
    visible: {
      BTNSAVE: "N",
      BTNCANCEL: "N",
      STSADDRESS: "N",
      IDDATE_PLACE2: "N",
      FKIDDATE_PLACE2: "N",
      IDINDEP_PSO_OFF: "Y",
      FKIDINDEP_PSO_OFF: "Y",
      IDDATE: "Y",
      FKIDDATE: "Y",
      "": "",
    },
    addFields: {},
    breadCrumbs: [
      { text: "Личный кабинет", href: "/cabinet/55/0/701" },
      { text: "Мои случаи", to: "/cabinet/55/0/713" },
      {
        text: "Карточка страхового случая",
        to: "/cabinet/55/0/946/3410/A9C5522BC9A2F86589DCE0E10E858B76",
      },
      { text: "Запись на осмотр ТС " },
    ],
    itemId: "994",
  },
};
export const fetchDicDate = [
  {
    ID: 290041,
    SNAME: "22.04.2024 (Понедельник) 09:00-16:00",
    text: "22.04.2024 (Понедельник) 09:00-16:00",
    value: 290041,
  },
  {
    ID: 290042,
    SNAME: "23.04.2024 (Вторник) 09:00-16:00",
    text: "23.04.2024 (Вторник) 09:00-16:00",
    value: 290042,
  },
  {
    ID: 290043,
    SNAME: "24.04.2024 (Среда) 09:00-16:00",
    text: "24.04.2024 (Среда) 09:00-16:00",
    value: 290043,
  },
];

export const fetchDicDep = [
  {
    ID: 43,
    SNAME: "450071, Башкортостан Респ, Уфа г, 50 лет СССР ул, д 27",
    text: "450071, Башкортостан Респ, Уфа г, 50 лет СССР ул, д 27",
    value: 43,
  },
  {
    ID: 1862,
    SNAME: "670047, Бурятия Респ, Улан-Удэ г, Сахьяновой ул, д 9В,",
    text: "670047, Бурятия Респ, Улан-Удэ г, Сахьяновой ул, д 9В,",
    value: 1862,
  },
  {
    ID: 1743,
    SNAME: "367912, Дагестан Респ, Махачкала г, Дагестанская ул, стр 49",
    text: "367912, Дагестан Респ, Махачкала г, Дагестанская ул, стр 49",
    value: 1743,
  },
];
