export default {
  wizardCursor: [
    {
      MENUCUR: [
        {
          LDELETE: false,
          IDADMMENUTYPE: 9,
          SNAME: "Ввод данных",
          LMODALFORMSTYLE: false,
          NONETOMANY: 0,
          LNEW: true,
          LEDIT: true,
          NORDER: 1,
          LNOTCARD: false,
          ACTIONSCUR: [],
          ID: 12820,
          LFIRSTLOADRECORD: true,
          IDITEM: 1105,
          ONETOMANYCUR: [],
          IDPARENT: 0,
          LPRINT: false,
          LNEWRECORDMETHOD: true,
        },
      ],
      SNAME: "Ввод данных",
      NORDER: 1,
      LOPENLIST: false,
      ID: 4540,
      NITEMPARENTMENU: 1081,
      NITEM: 1105,
      IDADMMODULE: 55,
    },
    {
      MENUCUR: [
        {
          LDELETE: false,
          IDADMMENUTYPE: 9,
          SNAME: "Водители",
          LMODALFORMSTYLE: false,
          NONETOMANY: 0,
          LNEW: true,
          LEDIT: true,
          NORDER: 2,
          LNOTCARD: false,
          ACTIONSCUR: [],
          ID: 12863,
          LFIRSTLOADRECORD: true,
          IDITEM: 1106,
          ONETOMANYCUR: [],
          IDPARENT: 0,
          LPRINT: false,
          LNEWRECORDMETHOD: false,
        },
      ],
      SNAME: "Водители",
      NORDER: 2,
      LOPENLIST: false,
      ID: 4541,
      NITEMPARENTMENU: 1081,
      NITEM: 1106,
      IDADMMODULE: 55,
    },
    {
      MENUCUR: [
        {
          LDELETE: false,
          IDADMMENUTYPE: 9,
          SNAME: "Сроки страхования",
          LMODALFORMSTYLE: false,
          NONETOMANY: 0,
          LNEW: true,
          LEDIT: true,
          NORDER: 3,
          LNOTCARD: false,
          ACTIONSCUR: [],
          ID: 12865,
          LFIRSTLOADRECORD: true,
          IDITEM: 1096,
          ONETOMANYCUR: [],
          IDPARENT: 0,
          LPRINT: false,
          LNEWRECORDMETHOD: false,
        },
      ],
      SNAME: "Сроки страхования",
      NORDER: 3,
      LOPENLIST: false,
      ID: 4542,
      NITEMPARENTMENU: 1081,
      NITEM: 1096,
      IDADMMODULE: 55,
    },
    {
      MENUCUR: [
        {
          LDELETE: false,
          IDADMMENUTYPE: 9,
          SNAME: "Точный расчет",
          LMODALFORMSTYLE: false,
          NONETOMANY: 0,
          LNEW: true,
          LEDIT: true,
          NORDER: 4,
          LNOTCARD: false,
          ACTIONSCUR: [
            {
              LUSEINCARD: true,
              LIDLIST: false,
              LSELECTDEFAULT: false,
              LINBUTTONS: false,
              NITEM: 1098,
              LCREATEBUTTON: true,
              LCHECKACCESS: false,
              LFROMDATASET: false,
              LINLIST: false,
              LOUTPARAM: false,
              LWITHCOMMIT: false,
              ID: 45810,
              LCURWINDOW: true,
              LMULTISELECT: false,
              SNAME: "Оформить полис",
              LFREEZONE: false,
              LREQUESTCODE: false,
              LCLOSEAFTER: false,
              LINACTIONS: true,
              LREFRESH: false,
              REL: "1097EA82970F7FDF2682CDD517A82619",
              SFIELD: "id",
              NTYPE: 38,
              LHIDEDLG: true,
              IDADMMODULE: 55,
              LNEEDPARAM: false,
              LHIDEINLIST: false,
              LTOOLBAR: false,
            },
            {
              LUSEINCARD: true,
              LIDLIST: false,
              LSELECTDEFAULT: false,
              LINBUTTONS: false,
              NITEM: 1098,
              LCREATEBUTTON: true,
              LCHECKACCESS: false,
              LFROMDATASET: false,
              LINLIST: false,
              LOUTPARAM: false,
              LWITHCOMMIT: false,
              ID: 45817,
              LCURWINDOW: false,
              LMULTISELECT: false,
              SNAME: "Рассчитать",
              LFREEZONE: false,
              LREQUESTCODE: false,
              LCLOSEAFTER: false,
              LINACTIONS: true,
              LREFRESH: false,
              REL: "1D8B0CEF4EB87BBE11D740A822D86E43",
              SFIELD: "id",
              NTYPE: 38,
              LHIDEDLG: true,
              IDADMMODULE: 55,
              LNEEDPARAM: false,
              LHIDEINLIST: false,
              LTOOLBAR: false,
            },
            {
              LUSEINCARD: true,
              LIDLIST: false,
              LSELECTDEFAULT: false,
              LINBUTTONS: false,
              NITEM: 1098,
              LCREATEBUTTON: true,
              LCHECKACCESS: false,
              LFROMDATASET: false,
              LINLIST: false,
              LOUTPARAM: true,
              LWITHCOMMIT: false,
              ID: 45818,
              LCURWINDOW: false,
              LMULTISELECT: false,
              SNAME: "Загрузить документы",
              LFREEZONE: false,
              LREQUESTCODE: false,
              LCLOSEAFTER: false,
              LINACTIONS: true,
              LREFRESH: false,
              REL: "98B583007C8569477D71A1BEA800336F",
              SFIELD: "id",
              NTYPE: 4,
              LHIDEDLG: false,
              IDADMMODULE: 55,
              LNEEDPARAM: false,
              LHIDEINLIST: false,
              LTOOLBAR: false,
            },
          ],
          ID: 12867,
          LFIRSTLOADRECORD: true,
          IDITEM: 1098,
          ONETOMANYCUR: [],
          IDPARENT: 0,
          LPRINT: false,
          LNEWRECORDMETHOD: false,
        },
      ],
      SNAME: "Точный расчет",
      NORDER: 4,
      LOPENLIST: false,
      ID: 4539,
      NITEMPARENTMENU: 1081,
      NITEM: 1098,
      IDADMMODULE: 55,
    },
    {
      MENUCUR: [
        {
          LDELETE: false,
          IDADMMENUTYPE: 9,
          SNAME: "Загрузка документов",
          LMODALFORMSTYLE: false,
          NONETOMANY: 0,
          LNEW: false,
          LEDIT: true,
          NORDER: 5,
          LNOTCARD: false,
          ACTIONSCUR: [
            {
              LUSEINCARD: false,
              LIDLIST: false,
              LSELECTDEFAULT: false,
              LINBUTTONS: false,
              NITEM: 1100,
              LCREATEBUTTON: false,
              LCHECKACCESS: false,
              LFROMDATASET: false,
              LINLIST: false,
              LOUTPARAM: false,
              LWITHCOMMIT: false,
              ID: 45757,
              LCURWINDOW: false,
              LMULTISELECT: false,
              SNAME: "Обновить статус проверки",
              LFREEZONE: false,
              LREQUESTCODE: false,
              LCLOSEAFTER: false,
              LINACTIONS: true,
              LREFRESH: false,
              REL: "71A430C9C1E97D4C61ECB3AC352426FE",
              SFIELD: "dual",
              NTYPE: 39,
              LHIDEDLG: true,
              IDADMMODULE: 55,
              LNEEDPARAM: false,
              LHIDEINLIST: false,
              LTOOLBAR: false,
            },
          ],
          ID: 12873,
          LFIRSTLOADRECORD: true,
          IDITEM: 1100,
          ONETOMANYCUR: [],
          IDPARENT: 0,
          LPRINT: false,
          LNEWRECORDMETHOD: false,
        },
      ],
      SNAME: "Загрузка документов",
      NORDER: 5,
      LOPENLIST: false,
      ID: 4586,
      NITEMPARENTMENU: 1081,
      NITEM: 1100,
      IDADMMODULE: 55,
    },
    {
      MENUCUR: [
        {
          LDELETE: false,
          IDADMMENUTYPE: 9,
          SNAME: "Подтверждение",
          LMODALFORMSTYLE: false,
          NONETOMANY: 0,
          LNEW: true,
          LEDIT: true,
          NORDER: 6,
          LNOTCARD: false,
          ACTIONSCUR: [
            {
              LUSEINCARD: true,
              LIDLIST: false,
              LSELECTDEFAULT: false,
              LINBUTTONS: false,
              NITEM: 1101,
              LCREATEBUTTON: false,
              LCHECKACCESS: false,
              LFROMDATASET: false,
              LINLIST: false,
              LOUTPARAM: false,
              LWITHCOMMIT: false,
              ID: 45779,
              LCURWINDOW: true,
              LMULTISELECT: false,
              SCONST: "Mobile.ClientUtils.SendEmail",
              SNAME: "Получить код",
              LFREEZONE: false,
              LREQUESTCODE: false,
              LCLOSEAFTER: false,
              LINACTIONS: true,
              LREFRESH: false,
              REL: "6EC92D2A8A30D8E6717C470A751F1486",
              SFIELD: "id",
              NTYPE: 4,
              LHIDEDLG: true,
              IDADMMODULE: 55,
              LNEEDPARAM: false,
              LHIDEINLIST: false,
              LTOOLBAR: false,
            },
            {
              LUSEINCARD: true,
              LIDLIST: false,
              LSELECTDEFAULT: false,
              LINBUTTONS: false,
              NITEM: 1101,
              LCREATEBUTTON: false,
              LCHECKACCESS: false,
              LFROMDATASET: false,
              LINLIST: false,
              LOUTPARAM: false,
              LWITHCOMMIT: false,
              ID: 45780,
              LCURWINDOW: false,
              LMULTISELECT: false,
              SCONST: "v4.osagoutils_web.SendCodeForOsago",
              SNAME: "Получить код",
              LFREEZONE: false,
              LREQUESTCODE: false,
              LCLOSEAFTER: false,
              LINACTIONS: true,
              LREFRESH: false,
              REL: "1AF0CA5D79045665EC682E24BC93B453",
              SFIELD: "id",
              NTYPE: 56,
              LHIDEDLG: true,
              IDADMMODULE: 55,
              LNEEDPARAM: false,
              LHIDEINLIST: false,
              LTOOLBAR: false,
            },
            {
              LUSEINCARD: true,
              LIDLIST: false,
              LSELECTDEFAULT: false,
              LINBUTTONS: false,
              NITEM: 1101,
              LCREATEBUTTON: false,
              LCHECKACCESS: false,
              LFROMDATASET: false,
              LINLIST: false,
              LOUTPARAM: true,
              LWITHCOMMIT: false,
              ID: 45781,
              LCURWINDOW: true,
              LMULTISELECT: false,
              SCONST: "v4.osagoutils_web.GenerateUrlExactCalc",
              SNAME: "Изменить данные",
              LFREEZONE: false,
              LREQUESTCODE: false,
              LCLOSEAFTER: false,
              LINACTIONS: true,
              LREFRESH: false,
              REL: "45492EEB407F35E1DB016BCF21AA32E4",
              SFIELD: "id",
              NTYPE: 4,
              LHIDEDLG: true,
              IDADMMODULE: 55,
              LNEEDPARAM: false,
              LHIDEINLIST: false,
              LTOOLBAR: false,
            },
          ],
          ID: 12880,
          LFIRSTLOADRECORD: true,
          IDITEM: 1101,
          ONETOMANYCUR: [],
          IDPARENT: 0,
          LPRINT: false,
          LNEWRECORDMETHOD: false,
        },
      ],
      SNAME: "Подтверждение",
      NORDER: 6,
      LOPENLIST: false,
      ID: 4612,
      NITEMPARENTMENU: 1081,
      NITEM: 1101,
      IDADMMODULE: 55,
    },
    {
      MENUCUR: [
        {
          LDELETE: false,
          IDADMMENUTYPE: 9,
          SNAME: "Оплата",
          LMODALFORMSTYLE: false,
          NONETOMANY: 0,
          LNEW: true,
          LEDIT: true,
          NORDER: 7,
          LNOTCARD: false,
          ACTIONSCUR: [
            {
              LUSEINCARD: true,
              LIDLIST: false,
              LSELECTDEFAULT: false,
              LINBUTTONS: false,
              NITEM: 1102,
              LCREATEBUTTON: false,
              LCHECKACCESS: false,
              LFROMDATASET: false,
              LINLIST: false,
              LOUTPARAM: true,
              LWITHCOMMIT: false,
              ID: 45847,
              LCURWINDOW: false,
              LMULTISELECT: false,
              SCONST: "v4.osagoutils_web.OpenPayLinkButton",
              SNAME: "Оплатить",
              LFREEZONE: false,
              LREQUESTCODE: false,
              LCLOSEAFTER: false,
              LINACTIONS: true,
              LREFRESH: false,
              REL: "2DC054617F84973E65F2BD7DE99F8835",
              SFIELD: "id",
              NTYPE: 4,
              LHIDEDLG: true,
              IDADMMODULE: 55,
              LNEEDPARAM: false,
              LHIDEINLIST: false,
              LTOOLBAR: false,
            },
            {
              LUSEINCARD: true,
              LIDLIST: false,
              LSELECTDEFAULT: false,
              LINBUTTONS: false,
              NITEM: 1102,
              LCREATEBUTTON: false,
              LCHECKACCESS: false,
              LFROMDATASET: false,
              LINLIST: false,
              LOUTPARAM: false,
              LWITHCOMMIT: false,
              ID: 45864,
              LCURWINDOW: false,
              LMULTISELECT: false,
              SCONST: "КИД НС АВТО",
              SNAME: "Скачать КИД",
              LFREEZONE: false,
              IDREPORT: 14770,
              LREQUESTCODE: false,
              LCLOSEAFTER: false,
              LINACTIONS: true,
              LREFRESH: false,
              REL: "D7D40B7944220F8560CA6DF545FF5ECE",
              SFIELD: "id",
              NTYPE: 3,
              LHIDEDLG: true,
              IDADMMODULE: 55,
              LNEEDPARAM: false,
              LHIDEINLIST: false,
              LTOOLBAR: false,
            },
            {
              LUSEINCARD: true,
              LIDLIST: false,
              LSELECTDEFAULT: false,
              LINBUTTONS: false,
              NITEM: 1102,
              LCREATEBUTTON: false,
              LCHECKACCESS: false,
              LFROMDATASET: false,
              LINLIST: false,
              LOUTPARAM: false,
              LWITHCOMMIT: false,
              ID: 45865,
              LCURWINDOW: false,
              LMULTISELECT: false,
              SCONST: "КИД РАП",
              SNAME: "Скачать КИД",
              LFREEZONE: false,
              IDREPORT: 14768,
              LREQUESTCODE: false,
              LCLOSEAFTER: false,
              LINACTIONS: true,
              LREFRESH: false,
              REL: "858351A3277B78B9A079A8A6A15E37BD",
              SFIELD: "id",
              NTYPE: 3,
              LHIDEDLG: true,
              IDADMMODULE: 55,
              LNEEDPARAM: false,
              LHIDEINLIST: false,
              LTOOLBAR: false,
            },
            {
              LUSEINCARD: true,
              LIDLIST: false,
              LSELECTDEFAULT: false,
              LINBUTTONS: false,
              NITEM: 1102,
              LCREATEBUTTON: false,
              LCHECKACCESS: false,
              LFROMDATASET: false,
              LINLIST: false,
              LOUTPARAM: false,
              LWITHCOMMIT: false,
              ID: 45863,
              LCURWINDOW: false,
              LMULTISELECT: false,
              SCONST: "КИД Столкновение",
              SNAME: "Скачать КИД",
              LFREEZONE: false,
              IDREPORT: 14766,
              LREQUESTCODE: false,
              LCLOSEAFTER: false,
              LINACTIONS: true,
              LREFRESH: false,
              REL: "49B35BA6676062477D390498FD125774",
              SFIELD: "id",
              NTYPE: 3,
              LHIDEDLG: true,
              IDADMMODULE: 55,
              LNEEDPARAM: false,
              LHIDEINLIST: false,
              LTOOLBAR: false,
            },
            {
              LUSEINCARD: true,
              LIDLIST: false,
              LSELECTDEFAULT: false,
              LINBUTTONS: false,
              NITEM: 1102,
              LCREATEBUTTON: false,
              LCHECKACCESS: false,
              LFROMDATASET: false,
              LINLIST: false,
              LOUTPARAM: false,
              LWITHCOMMIT: false,
              ID: 45848,
              LCURWINDOW: false,
              LMULTISELECT: false,
              SNAME: "Обновить статус оплаты",
              LFREEZONE: false,
              LREQUESTCODE: false,
              LCLOSEAFTER: false,
              LINACTIONS: true,
              LREFRESH: false,
              REL: "AA3CF7B0091C3CC5CFF25FED9F294632",
              SFIELD: "dual",
              NTYPE: 39,
              LHIDEDLG: true,
              IDADMMODULE: 55,
              LNEEDPARAM: false,
              LHIDEINLIST: false,
              LTOOLBAR: false,
            },
            {
              LUSEINCARD: true,
              LIDLIST: false,
              LSELECTDEFAULT: false,
              LINBUTTONS: false,
              NITEM: 1102,
              LCREATEBUTTON: false,
              LCHECKACCESS: false,
              LFROMDATASET: false,
              LINLIST: false,
              LOUTPARAM: true,
              LWITHCOMMIT: false,
              ID: 45849,
              LCURWINDOW: false,
              LMULTISELECT: false,
              SCONST: "v4.osagoutils_web.GenerateUrlExactCalc",
              SNAME: "Внести изменения",
              LFREEZONE: false,
              LREQUESTCODE: false,
              LCLOSEAFTER: false,
              LINACTIONS: true,
              LREFRESH: false,
              REL: "B868067CE42BA133E1BBAED8F7F04873",
              SFIELD: "id",
              NTYPE: 4,
              LHIDEDLG: true,
              IDADMMODULE: 55,
              LNEEDPARAM: false,
              LHIDEINLIST: false,
              LTOOLBAR: false,
            },
            {
              LUSEINCARD: true,
              LIDLIST: false,
              LSELECTDEFAULT: false,
              LINBUTTONS: false,
              NITEM: 1102,
              LCREATEBUTTON: false,
              LCHECKACCESS: false,
              LFROMDATASET: false,
              LINLIST: false,
              LOUTPARAM: false,
              LWITHCOMMIT: false,
              ID: 45866,
              LCURWINDOW: false,
              LMULTISELECT: false,
              SCONST: "КИД НС АВТО",
              SNAME: "Скачать КИД",
              LFREEZONE: false,
              IDREPORT: 14770,
              LREQUESTCODE: false,
              LCLOSEAFTER: false,
              LINACTIONS: true,
              LREFRESH: false,
              REL: "4E541F8391A818D9D4D1E7608BEED039",
              SFIELD: "id",
              NTYPE: 3,
              LHIDEDLG: true,
              IDADMMODULE: 55,
              LNEEDPARAM: false,
              LHIDEINLIST: false,
              LTOOLBAR: false,
            },
          ],
          ID: 12913,
          LFIRSTLOADRECORD: true,
          IDITEM: 1102,
          ONETOMANYCUR: [],
          IDPARENT: 0,
          LPRINT: false,
          LNEWRECORDMETHOD: false,
        },
      ],
      SNAME: "Оплата",
      NORDER: 7,
      LOPENLIST: false,
      ID: 4629,
      NITEMPARENTMENU: 1081,
      NITEM: 1102,
      IDADMMODULE: 55,
    },
  ],
  wizardIDCARDS: [1105, 1106, 1096, 1098, 1100, 1101, 1102],
  wizardNavigation: {
    current: { REL: "D5364FE82A297F83B2BE0102176AC40D", IDCARD: 1105 },
    next: { REL: "43DDF91ACD33959D1DE8D34E9DA69436", IDCARD: 1106 },
    back: {},
  },
  wizardRels: [
    "B05C21BB39B4BD3F752995DF424B521B",
    "D5364FE82A297F83B2BE0102176AC40D",
    "43DDF91ACD33959D1DE8D34E9DA69436",
    "2DF1E61669C3F24548055C0752E9E0A8",
    "53A4B7885D775D90530C082566E5B6D1",
    "FE4967D4377722F7DE592038342978F9",
    "0A769EDAD05963058AEB48134FBE38FF",
  ],
};
