export const ControlVariantPolicyProps = {
  label: "<b>Вариант полиса</b>",
  type: "VariantPolicy",
  id: "1040",
  fieldId: 61311,
  cols: 12,
  colSm: 12,
  colMd: 12,
  isMask: false,
  colLg: 14,
  width: "100%",
  name: "IDPOLICYVARIANT",
  cssClass: "",
  webId: "",
  visible: true,
  required: false,
  page: 1,
  readonly: false,
  control: null,
  state: null,
  checked: null,
  error: null,
  isRelation: true,
  fieldRelation: null,
  isTab: false,
  value: '{"IDVARIANT":2,"IDFRNANCHISE":null}',
  options: [
    {
      IDFRANCHISE: null,
      SREPAIR: "Ремонт без справок",
      SACCIDENT: "Последствия ДТП",
      SACTIONS: "Действия 3-х лиц",
      SNAME: "scaption",
      SDESCRIPTION: "true",
      SFOREIGNOBJECTS: "Падение или Попадание инородных предметов",
      ID: 1,
      NPRICE: 0,
      SFRANCHISE: "Франшиза",
      STHEFTVEH: "Хищение ТС",
      SNOEVENTRESTRICTIONS: "Без ограничений по страховым событиям",
      text: "scaption",
      value: 1,
      S_ORDER: [
        "sfranchise",
        "saccident",
        "sforeignobjects",
        "stheftveh",
        "sactions",
        "srepair",
        "snoeventrestrictions",
      ],
      S_INFO: ["Тест1", "Тест2", "Тест3", "Тест4", "Тест5", "Тест6", "Тест7"],
    },
    {
      IDFRANCHISE: null,
      SREPAIR: "N",
      SACCIDENT: "N",
      SACTIONS: "N",
      SNAME: "Только Хищение",
      SFOREIGNOBJECTS: "N",
      ID: 2,
      SDESCRIPTION: "false",
      NPRICE: 10000,
      SFRANCHISE: "N",
      STHEFTVEH: "Y",
      SNOEVENTRESTRICTIONS: "Y",
      text: "Только Хищение",
      value: 2,
    },
    {
      IDFRANCHISE: null,
      SREPAIR: "Y",
      SACCIDENT: "Y",
      SACTIONS: "Y",
      SNAME: "Ущерб + хищение",
      SFOREIGNOBJECTS: "Y",
      SDESCRIPTION: "false",
      ID: 3,
      NPRICE: 20000,
      SFRANCHISE: [
        { sname: "30 000", id: 1 },
        { sname: "60 000", id: 2 },
      ],
      STHEFTVEH: "Y",
      SNOEVENTRESTRICTIONS: "Y",
      text: "Ущерб + хищение",
      value: 3,
    },
    {
      IDFRANCHISE: null,
      SREPAIR: "Y",
      SACCIDENT: "Y",
      SACTIONS: "Y",
      SNAME: "Ущерб + хищение + ",
      SFOREIGNOBJECTS: "Y",
      SDESCRIPTION: "false",
      ID: 4,
      NPRICE: 30000,
      SFRANCHISE: "Y",
      STHEFTVEH: "Y",
      SNOEVENTRESTRICTIONS: "Y",
      text: "Ущерб + хищение + ",
      value: 4,
    },
  ],
};
